### ISSUE TITLE
Progress messaging

### ISSUE THREAD

**Issue by cosmo0** [JimBobSquarePants/ImageProcessor#109]
I have integrated the library in my client app.  
The problem is that when I apply a filter, users do not get feedback on the filter progression.

It would be awesome to get progress indication. Something added to `IGraphicsProcessor`.

I think using an observer pattern similar to [the event aggregator available in Caliburn.Micro](http://caliburnmicro.com/documentation/event-aggregator) for instance.
Basically, it uses an event aggregator (through an interface and dependency injection), which is a class handling messages bubbling up the class tree, to which other classes can subscribe to through the `IHandle<T>` interface.
The source code for these is available... [around here I guess](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro/EventAggregator.cs). I'm not sure how it's implemented, but you can probably inspire yourself from this. 

It can also be implemented through more classic events and event handlers.
Please note that this code is hand-typed and I don't know if it even compiles :smile: 

````csharp
public interface IGraphicsProcessor {
    delegate void ProgressedEventHandler(object sender, ProgressedEventArgs e);
    event ProgressedEventHandler OnProgressed;
}

public class MyProcessor : IGraphicsProcessor {
    public Image ProcessImage(ImageFactory factory) {
        // TODO: do some work
        if (OnProgressed != null) { OnProgressed(this, new ProgressedEventArgs { percent = 10 }; }
        // TODO: do some more work
        if (OnProgressed != null) { OnProgressed(this, new ProgressedEventArgs { percent = 100 }; }
    }
}

public class MyApp {
    public MyApp() {
        MyProcessor p = new MyProcessor();
        p.OnProgressed += new ProgressedEventHandler(processor_OnChanged);
    }

    private static void processor_OnChanged(object sender, ProgressedEventArgs e) {
        MessageBox.Show("progress: " + e.percent);
    }
}
````

**Comment by voidstar69** [comment]
I am interested on working on this issue.

IGraphicsProcessor is an interface in the V2 branch. The V3 branch uses the IImageProcessor interface. It looks to me like the V2 filters are are single-threaded, so a callback progress indicator is simple to implement, but the V3 filters are multi-threaded (via ParallelImageProcessor and the Tasks library). So a callback progress indicator in V3 might be invoked from any task (thread), which would need to be handled by the client code.

Perhaps the Tasks library has some functionality to allow progress notification to be reported from each task to ParallelImageProcessor, which could then send progress notifications to the client on the calling thread?

**Comment by JimBobSquarePants** [comment]
Hi there,

I'd love to see what you could implement for either. A huge :+1: from me. 

I agree that for V2 it should be a simple addition, for V3 (I think I'm going to rename that btw to Core.V1) I don't know. I thought about adding something to `ParallelImageProcessor` since that is the single point we can grab the sum of the processor count and provide accurate-ish feedback. Processors can be nested though so it makes it extremely tricky.

**Comment by voidstar69** [comment]
Hi,

I have now implemented the progress callback for the V3 branch: https://github.com/voidstar69/ImageProcessor

I decided to let the client code handle multi-threaded callbacks, rather than have `ParallelImageProcessor` try to serialise these into callbacks on the client thread.

The callback fires after each (source image) row is processed (potentially in any order, due to multi-threading). A typical filter that processes each row only once simply needs to call `ParallelImageProcessor.OnRowProcessed`. For now I have only added this call to the Brightness filter, but it needs to be added to every filter.

I have modified the `FilterImage` test to check that the callback triggers for rows roughly in order, with some variability allowed due to multi-threading. I am not certain that this check would be valid on all platforms, so a smarter test may be required (e.g. check that every row is processed, and only once each).

Let me know what you think of this code. I am happy to make any changes that you suggest.
Thanks

**Comment by JimBobSquarePants** [comment]
I like this! Any noticeable performance cost from adding the functionality?

**Comment by voidstar69** [comment]
Nothing conclusive. The existing stopwatch timing seems too variable for performance testing - a good performance test would probably execute a single filter many times to ensure code is JITed and cached, throw away the highest and lowest times, and average the rest.

Using the existing stopwatch timing, I only know how to view the trace output via debugging the code and looking in the Debug window. I did this (with my laptop in High Performance mode to avoid CPU down-scaling), and got the following results:

Old code, release mode, debugging, trace output.
1st run:
`Brightness-50: 1396ms
Brightness-50: 190ms
Brightness-50: 415ms
Brightness-50: 121ms`
2nd run:
`Brightness-50: 1406ms
Brightness-50: 183ms
Brightness-50: 413ms
Brightness-50: 116ms`

New code, release mode, debugging, trace output.
1st run:
`Brightness-50: 1543ms
Brightness-50: 149ms
Brightness-50: 447ms
Brightness-50: 111ms`
2nd run:
`Brightness-50: 1341ms
Brightness-50: 164ms
Brightness-50: 471ms
Brightness-50: 107ms`


I will change all the filters to support the progress indicator callback, then we will see if the overall execution time of the `FilterImage` test changes.

**Comment by JimBobSquarePants** [comment]
:smile: Yeah that doesn't yield much discernible difference. `Interlocked.Add` is supposed to do millions of operations a second so I doubt it will. 

Looking forward to seeing that in place. I'll look into coding out a nice way to test performance of individual processors. and the encoders/decoders separately.

**Comment by voidstar69** [comment]
I changed all filters and samplers to provide progress updated, and submitted this as PR #310

**Comment by JimBobSquarePants** [comment]
@cosmo0 @voidstar69 What are your thoughts on adding similar functionality to the Framework version? I'm concerned that we cannot now change the `IGraphicsProcessor` interface without a major version.

**Comment by voidstar69** [comment]
@JimBobSquarePants I will have a look at the Framework version this weekend, to see how much work is involved in adding progress updates.

We can make the change backwards compatible (i.e. the progress callback is optional) - does this then require a major new version of ImageProcessing for Framework?

**Comment by cosmo0** [comment]
> I'm concerned that we cannot now change the IGraphicsProcessor interface without a major version.

Large breaking changes in the API might require a new major version, but I don't think just introducing a new feature does.

**Comment by JimBobSquarePants** [comment]
If we can get by without changing the interface then minor version, any interface changes will require a major version. I've made that mistake before. It ain't pretty.

**Comment by voidstar69** [comment]
It is possible to add the OnProgress event to all classes that implement IGraphicsProcessor, without adding it to IGraphicsProcessor. Not the cleanest approach, but it would then not require a major version.
Then when you have a reason for another major version, the OnProgress event can be added to IGraphicsProcessor.
The downside is that any code that generically handles IGraphicsProcessor-derived objects, would not have access to the OnProgress event. However most client code probably uses the derived classes directly.

**Comment by voidstar69** [comment]
Looking more closely at this, I believe a progress callback is generally not possible for the Framework branch. The issue is that most processors make a single call to a method of `System.Drawing.Graphics` or `System.Drawing.Image` to perform most of the work, and these classes do not provide any progress callbacks. I tried using `System.Drawing.Graphics.DrawImageAbort` as a progress callback, but this seems to be called only once per call to `System.Drawing.Graphics.DrawImage`.

Only processors that perform pixel manipulation themselves could provide a progress callback. About a third of processors do this:

- Alpha
- Convolution (GaussianBlur, GaussianSharpen)
- ConvolutionFilter (DetectEdges)
- Gamma
- Halftone
- Hue
- Pixelate
- ReplaceColor

Overall I think there is not much point implementing a progress callback for the Framework branch.

**Comment by JimBobSquarePants** [comment]
@voidstar69. I concur, I was thinking about it today and drew exactly the same conclusion.  I vote for closing the issue.

**Comment by voidstar69** [comment]
@JimBobSquarePants I agree, this issue should be closed.

Hopefully the Core version will eventually become the single standard version of ImageProcessor for all platforms, and so all platforms will then have progress callbacks.

**Comment by voidstar69** [comment]
@cosmo0 Are you happy for this issue to be closed?

**Comment by cosmo0** [comment]
Sure !
