### ISSUE TITLE
.Net 3.5

### ISSUE THREAD

**Issue by doczoidberg** [JimBobSquarePants/ImageProcessor#119]
is there any way to use this library with .Net 3.5?

**Comment by JimBobSquarePants** [comment]
I'm afraid not and I very much doubt it is possible without a lot of work.

I haven't made an attempt to do so and off the top of my head I can already envisage several issues. I won't be trying to do so either.

NET 4.0 came out in 2009 so that's already 5 1/2 years ago and NET 4.5 came out 2 1/2 years ago. If I were you I really would try your very best to upgrade to the later frameworks. It will only benefit you to do so.

**Comment by doczoidberg** [comment]
unfortunately some customers still use Windows XP

**Comment by JimBobSquarePants** [comment]
That is true but they are a small minority. Microsoft has themselves ceased support for XP so you can't really expect an open source project to maintain support for it whilst also work towards future performance improvements. 

Take a look at the contributors graph for the project. https://github.com/JimBobSquarePants/ImageProcessor/graphs/contributors 

Whilst there's a lot of stars and forks of the project, a vast majority of the work is done by me and I simply cannot devote the time to provide backwards compatibility.

**Comment by doczoidberg** [comment]
I can understand it
