### ISSUE TITLE
No way to AutoRotate and save Exif

### ISSUE THREAD

**Issue by musukvl** [JimBobSquarePants/ImageProcessor#122]
As I see Autorotate function can be called only if new ImageFactory(preserveExifData: true). But what if  I what only autorotate, but no lose gps and other Exif stuff. 
Why is it  not possible only change orientation fied of jpeg EXIF?

**Comment by JimBobSquarePants** [comment]
I think you've missed the point of what the method does. 

AutoRotate preserves any EXIF defined rotation stored in an image for when you are **not** preserving EXIF metadata. This ensures that your image does not rotate when the metadata is removed. 

Manipulating individual EXIF metadata tags is currently not supported. See issue #78 It's an incredibly complicated issue which is why it's been marked as 'help needed'. If you can provide support on that front then please do.
