### ISSUE TITLE
autoLoadServices attribute may not work

### ISSUE THREAD

**Issue by janrhansen** [JimBobSquarePants/ImageProcessor#124]
Hi James

I just upgraded from NuGet package 4.1.3 to 4.1.5 and my custom image handler no longer returned images :-/ After a quick compare I saw that the security.config default file that was written on top of my original one contained <services> instead of <services autoLoadServices="true">. As my image.axd service is loaded automatically I promptly added autoLoadServices="true", but then got this message:
Server Error in '/' Application.

Configuration Error

Description: An error occurred during the processing of a configuration file required to service this request. Please review the specific error details below and modify your configuration file appropriately. 

Parser Error Message: Unrecognized attribute 'autoLoadServices'. Note that attribute names are case-sensitive. 

Then I noted that you had done some changes related to the autoload handling (https://github.com/JimBobSquarePants/ImageProcessor/commit/65e95ad9cdc2bc87bda535ed13289310bf8c8db7), so I removed the attribute and added my image.axd handler to the configuration file, and now it works. 

So - is it intentional that the default security.config file cant also autoload handlers, so to say. Or am I misunderstanding things? I can't see what good autoload is for, if you can't use it along with the specified handlers. 

BR, Jan

**Comment by JimBobSquarePants** [comment]
Hi Jan,

I changed the behaviour so that by having a configuration file in place it will only load the services contained with the configuration file by default. Which reminds me... I need to update the documentation!

It was better for security and also meant that settings were loaded properly. The `autoLoadServices` property served no real function other than to cause confusion. 

To me, this makes sense. If you want to run everything as default. Don't add configuration. If you want to edit the defaults. Add the configuration and the system will run from that alone.

Cheers

James

**Comment by janrhansen** [comment]
Hi,

OK, that makes sense. So if I remove the configuration, I get the default behaviour - but if I add the configuration (which I need) I also have to add the LocalFileImageService to the configuration if I want to use the "default" behavour along with my own module?

/Jan

**Comment by JimBobSquarePants** [comment]
Yeah, that's right. It'll ensure that you only get what you need and make any issues easier to debug.

**Comment by janrhansen** [comment]
Alright - thank you :o)
