### ISSUE TITLE
Black borders when resizing an image

### ISSUE THREAD

**Issue by cosmo0** [JimBobSquarePants/ImageProcessor#127]
Hi !

We have an issue with image resizing in our new application's version : often, there are black borders appearing around resized images.

The developers I'm working with have created a sample application (using resize code from the actual app), that I have added on Github: https://github.com/cosmo0/ImageProcessor.Problems

If you run the app, click on the button, and check out the bin folder, you'll see a ProcessedImage.jpg file with black borders around it (that shouldn't be there).

Is it some bug in the library, or are we using the library wrong ?

Thanks for your help

**Comment by JimBobSquarePants** [comment]
Bonjour!

The problem is actually in your implementation. Yay!

`Resize()` defaults to `ResizeMode.Pad` which will pad the image if both the dimensions are set and if they do not match the aspect ratio of the initial image.

http://imageprocessor.org/imageprocessor/imagefactory/resize.html

Since jpegs do not have an alpha channel the background of the image will default to black when saved in that format - This is the default behaviour of the encoder so I didn't mess with it.

So you have three choices... 

1. Set the `ResizeMode` to another variable like `Crop` if you want to use those exact dimensions, `Max` if you want to set a maximum value for each dimension.
2. Use the `BackgroundColor()` method after the resize to set the colour to white or something else.
3. Use only one dimension so that the other one is automatically determined and the aspect ratio is preserved.


*Note*. In the code sample you provided you are creating a duplicate `Bitmap` to save the image. That's probably not wise for memory management. You can use the overload to save to the file directly.

    // Initialize the ImageFactory using the overload to preserve EXIF metadata.
    using (ImageFactory imageFactory = new ImageFactory(preserveExifData: false))
    {
        // Load, resize, set the format and quality and save an image.
        imageFactory.Load(inStream)
                    .Resize(resizeValue)
                    .Format(format)
                    .Save(outFileName);
    }

 If you need to use a stream you should probably use a `FileStream` to save the image.

    using (FileStream fileStream = File.Create(outFileName))
    {
        outStream.Seek(0, SeekOrigin.Begin);
        outStream.CopyTo(fileStream);
    }

Hope that helps. :smile:

**Comment by cosmo0** [comment]
Awesome! I'll transmit your informations to the developers. Thank you very much for your time! :smile:

**Comment by JimBobSquarePants** [comment]
No worries. Happy to help :smile:
