### ISSUE TITLE
Loading of all assemblies when loading an image

### ISSUE THREAD

**Issue by cosmo0** [JimBobSquarePants/ImageProcessor#134]
I just noticed this when running the app in debug mode: 
https://github.com/JimBobSquarePants/ImageProcessor/blob/master/src/ImageProcessor/Configuration/ImageProcessorBootstrapper.cs#L80

We have about 100 DLLs in there. Some of them are C++ (non-.Net) DLLs, so it throws a bunch of errors. Some of them weigh more than 10Mb. This doesn't seem very optimized... :/
I understand that you want to discover the available formats without explicitly linking or listing them, but is there a way to filter the loaded DLLs ?

**Comment by JimBobSquarePants** [comment]
Hmmm.... I guess we could optimize by filtering by some sort of naming convention. However, there isn't a convention and I don't know what people have called their stuff in the wild.

**Comment by cosmo0** [comment]
Maybe some sort of config (in a new `ImageProcessor.config` file) to disable auto-loading of other DLLs (which behaves like today by default), and another config with a regexp to filter the file names ?

I don't know about slowdowns, because it's always been this way (I just added the PDBs so I assume it used to do that without me knowing about it). I must assume loading 10mb files from the disk must slow down the processing in some way, not necessarily in a really significant way for my app, but maybe for others.

**Comment by JimBobSquarePants** [comment]
It'll only happen on first initialisation and is cached after that and shouldn't affect further processing. 

I loath the idea of adding config files to ImageProcessor, parts of it's charm is its install and go functionality.

**Comment by cosmo0** [comment]
Yes but you can use optional config files. Meaning that if the config file is not found, or if the value is not found in the config file, it has a default value, which behaves like today.
It would still work out-of-the-box, but could give users options to optimize some areas.

**Comment by JimBobSquarePants** [comment]
Feel free to have a tinker at that then, I'm a bit swamped at the mo. Remember.. v2 branch :wink:

**Comment by cosmo0** [comment]
Ok, not sure I'll have time just now either, but I'll think about it :smile:

**Comment by JimBobSquarePants** [comment]
Fixed in 2.2.1 I've replaced the type loader with a new optimized version that filters out a large number of known assemblies when looking for plugins..

**Comment by gabrielius** [comment]
I am experiencing a similar situation, when in use with AutoMapper. ImageProcessor for some reason tries to load AutoMapper, because one of the DLLs is referencing AutoMapper. However AutoMapper.dll is not even present in the *bin* folder, so don't know why ImageProcessor even tries to load that.

I was thinking, maybe it is possible to turn off plugin search via a config file?

**Comment by JimBobSquarePants** [comment]
Can you provide some sort of prove for this please?

**Comment by gabrielius** [comment]
Basically, I have two environments:
- Mine
- Client's. 

I am *not* experiencing problems, my client *does*.

I have an **App**, **Library**, **AutoMapper**. 

*App* references *Library*, which one method uses *AutoMapper*. However, *App* never calls that method, so *App* works on my PC *without* *AutoMapper*. Nevertheless, my client gets an exception, which StackTrace is below.

I use "2.2.6.0" version of ImageProcessor. Both, client and me use .NET Framework 4.5.

````
System.AggregateException: One or more errors occurred. ---> System.IO.FileLoadException: Could not load file or assembly 'AutoMapper, Version=3.3.1.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515) ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   --- End of inner exception stack trace ---
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at ImageProcessor.Common.Helpers.TypeFinder.GetAllAssemblies()
   at ImageProcessor.Common.Helpers.TypeFinder.GetFilteredAssemblies(IEnumerable`1 excludeFromResults, String[] exclusionFilter)
   at ImageProcessor.Common.Helpers.TypeFinder.GetAssembliesWithKnownExclusions(IEnumerable`1 excludeFromResults)
   at ImageProcessor.Configuration.ImageProcessorBootstrapper.LoadSupportedImageFormats()
   at ImageProcessor.Configuration.ImageProcessorBootstrapper..ctor()
   at ImageProcessor.Configuration.ImageProcessorBootstrapper.<.cctor>b__8()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at ImageProcessor.Imaging.Formats.FormatUtilities.GetFormat(Stream stream)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MyClass.ImageManipulation.Rotate(Byte[] imageData, Single degrees) in C:\Source\ImageManipulation.cs:line 31
````

**Comment by JimBobSquarePants** [comment]
Thanks for that. I appreciate it.

ImageProcessor will load a reference to the assembly but not try to parse the assembly to find any available types if it is in the excluded list.

That error is caused either by an Automapper.dll in the bin folder that is blocked as it was downloaded from the internet.... 

http://blogs.msdn.com/b/drew/archive/2009/12/24/xunit-and-td-net-fixing-the-attempt-was-made-to-load-an-assembly-from-a-network-location-problem.aspx

.... or because the assembly is somehow references from a remote location or a Virtual PC application when you try to load a file from linked folders on the hosting computer.

https://msdn.microsoft.com/en-us/library/dd409252%28VS.100%29.aspx?f=255&MSPPError=-2147217396

I would get him to check for the dll file first and see if it is blocked.

Theoretically I could add a IO exception to the test here and simply debug.log that kind of error. 

https://github.com/JimBobSquarePants/ImageProcessor/blob/d4171429ce470e890f76b0f2000120bf779791f2/src/ImageProcessor/Common/Helpers/TypeFinder.cs#L128

What do you think?

**Comment by gabrielius** [comment]
I think that would be OK. I will check the rest on my side. Thanks.

**Comment by LavenderDaisy** [comment]
I use imageFactory.Load(imgPath); as below:

           using (ImageFactory imageFactory = new ImageFactory(preserveExifData: true))
            {
                imageFactory.Load(imgPath);
                imageFactory.ReplaceColor(source, target, 128);

                using (MemoryStream ms = new MemoryStream())
                {
                    imageFactory.Save(ms);
                    return Image.FromStream(ms);
                }
            }

> It loads very slow on the first initialization,It takes 9965 ms to load all my assemblies which is not what I want . 
 

- ImageProcessor.Configuration.ImageProcessorBootstrapper.LoadSupportedImageFormats()  9833 ms
-      System.Linq.Enumerable.ToList(IEnumerable[TSource])   7724 ms
-     ImageProcessor.Configuration.ImageProcessorBootstrapper+<>c.<LoadSupportedImageFormats>b__18_0(Assembly)             7718ms
-      ImageProcessor.Common.Extensions.AssemblyExtensions.GetLoadableTypes(Assembly)  7718ms
-      System.Reflection.Assembly.GetTypes()                              7718ms


Can you give an access to change the **SupportedImageFormats** individually ,so that I can set that outside without load all my assemblies or just give a flag to Load all assemblies or not . I do a little change as below:


   
    **_public static bool LoadAssemblies=true;_**
        /// <summary>
        /// Creates a list, using reflection, of supported image formats that ImageProcessor can run.
        /// </summary>
        private void LoadSupportedImageFormats()
        {
            var formats = new List<ISupportedImageFormat>
            {
                new BitmapFormat(),
                new GifFormat(),
                new JpegFormat(),
                new PngFormat(),
                new TiffFormat()
            };

            Type type = typeof(ISupportedImageFormat);
            if (this.SupportedImageFormats == null)
            {
                _if(LoadAssemblies)
                {_
                var availableTypes =
                    TypeFinder.GetAssembliesWithKnownExclusions()
                        .SelectMany(a => a.GetLoadableTypes())
                        .Where(t => type.IsAssignableFrom(t) && t.IsClass && !t.IsAbstract)
                        .ToList();

                formats.AddRange(availableTypes.Select(f => Activator.CreateInstance(f) as ISupportedImageFormat).ToList());

                this.SupportedImageFormats = formats;
                }
                else
                {
                     this.SupportedImageFormats = formats;
                }
            }
        }
```
`

**Comment by JimBobSquarePants** [comment]
@LavenderDaisy I'm actually looking at that code for v3.

I'd actually like to drop all automatic assembly loading and make the process entirely manual.
