### ISSUE TITLE
Slow performance on VPS

### ISSUE THREAD

**Issue by srdjo** [JimBobSquarePants/ImageProcessor#153]
Hi all,

I have a following preset

<preset name="kocka-tag" value="cropentropycrop=30&#038;width=250&#038;height=180&#038;bgcolor=fff&#038;watermark=multicom.me&#038;color=fff&#038;fontsize=10&#038;fontopacity=50&#038;textshadow=true&#038;fontfamily=arial&#038;position=180,165"/>

When the page with 100 images is rendered, ImageProcessor uses 100% of CPU and my website becomes unresponsive until all images are loaded.

What might be the problem ?

**Comment by srdjo** [comment]
preset name="kocka-tag" value="cropentropycrop=30&#038;width=250&#038;height=180&#038;bgcolor=fff&#038;watermark=multicom.me&#038;color=fff&#038;fontsize=10&#038;fontopacity=50&#038;textshadow=true&#038;fontfamily=arial&#038;position=180,165"

**Comment by JimBobSquarePants** [comment]
What's this?

> value="cropentropycrop

Also, what are the specifications of the VPS, what version are you using? that kind of stuff...

**Comment by JimBobSquarePants** [comment]
Also, 100 images on one page without some sort of lazy loading mechanism. That's a performance nightmare.

**Comment by srdjo** [comment]
cropentropycrop removes the blank space around image - so I only get big picture.

I use GoDaddy VPS server with Intel Xeon e5-2640L processor and 3GB of RAM.

I used the imageresizing.net library before for the same thing and there were no problems, but it didnt have disk cache so I decided to give your library a try. It does the great job, but with this performance issue. It is used on an ecommerce site for displaying product images (20 products, 1 big picture, 4 small thumbs)

Original pictures are 500-900px max w/h jpg files.

You are right about lazy loading - I might try that. What concerns me are web search robots. I might have a website slowdown the next time crawler passes by.

**Comment by JimBobSquarePants** [comment]
That's the wrong syntax for Entropy Crop. You're lucky it works and it will not in the next release since I've rewritten the parser.

http://imageprocessor.org/imageprocessor-web/imageprocessingmodule/entropycrop/

Your watermark syntax is incorrect also.

http://imageprocessor.org/imageprocessor-web/imageprocessingmodule/watermark/

I very much doubt that ImageResizing.Net was doing the same function as you are requesting from ImageProcessor. Entropy cropping is a very expensive process which require both edge detection and binary threshold filtering to correctly identify the blank areas of an image. 

All this is done as much as possible in parallel to keep performance snappy.

https://github.com/JimBobSquarePants/ImageProcessor/blob/V2/src/ImageProcessor/Processors/EntropyCrop.cs#L62

I actually wrote the method for a very big commerce site and it is operating well for that environment.

What intrigues me most about your issue is that the way you are describing the scenario caching is not working. I cannot imagine a scenario where all 100 images are brand new and requested at the same time unless this was the first loading of the site page ever. Once an image has been processed subsequent requests should come from first the browser cache, or on hard reset the disk cache. If this is not happening then something is wrong with your setup. The default cache is also lasts for 1 year.

I wouldn't be worried about web crawlers. I would be more concerned about bandwidth. Imagine someone coming to your website on a mobile device. If every page is loading 100 images then their data costs will be through the roof!

**Comment by srdjo** [comment]
One big image is 7KB, and small ones are 2-3KB each - thats less then 1MB for the whole page.

I used lazy loading and it is working just fine now. Thanks for suggestion.

Can you just tell me how can I cleanup image cache ? When I add new products to the site, I generate 10-20 thumbs from which I select 3-5 images. How can I delete the others ? I delete the original image but what about generated thumbnails ?

**Comment by JimBobSquarePants** [comment]
Glad you've made some progress.

The cache is self cleaning. If the original files are updated the cache will replace all generated images. After the default period of a year after first generation the cache will delete the cached thumbnails. 

There's no explicit public method to delete a cached image as that would open the site up to DOS attacks but you can tell ImageProcessor.Web to store images for less time if they are likely to change often by installing the [ImageProcessor.Web.Config](https://www.nuget.org/packages/ImageProcessor.Web.Config/) package and editing the [cache.config](http://imageprocessor.org/imageprocessor-web/configuration/#cacheconfig) property `maxDays` 

Otherwise the algorithm for hashing urls to generate cache keys is [here](https://github.com/JimBobSquarePants/ImageProcessor/blob/V2/src/ImageProcessor.Web/Caching/ImageCacheBase.cs#L118). You could build something that searches for a specific thumbnail based on that hash.
