### ISSUE TITLE
Managed version of content-aware resizing

### ISSUE THREAD

**Issue by KvanTTT** [JimBobSquarePants/ImageProcessor#158]
There is managed implementation of CAIR seam carving (content-aware) algorithm: [Seam-Carving-Advanced](https://github.com/KvanTTT/Seam-Carving-Advanced).

It it possible to port it to your library. Is it necessary?

**Comment by JimBobSquarePants** [comment]
A managed implementation would be amazing! :smile:  I've been really unhappy with the way I've had to implement seam carving at the moment.

**Comment by JimBobSquarePants** [comment]
Would this be something you would be interested in adding to V3?

**Comment by KvanTTT** [comment]
I'am not interested in this library in near future :( I'am doing another things.

**Comment by dampee** [comment]
@KvanTTT how difficult would it to port?

**Comment by KvanTTT** [comment]
@dampee, I think it is not difficult. The only thing my library is using **unsafe** code snippent for performance reason. Are they allowed in ImageProcessor?

**Comment by JimBobSquarePants** [comment]
@KvanTTT  There's tons of unsafe code in Corefx https://github.com/dotnet/corefxlab/search?utf8=%E2%9C%93&q=unsafe so I'm not opposed to using it in ImageProcessor. 

I avoided it before as I was targeting some old PCL stuff (WP8) which didn't support it but I'm sure now there are places within my codebase which could benefit. Would need lots of testing to determine where though.

@dampee If you're gonna attempt a port I would test unsafe vs safe blocks to see whether there is a speedup since we're not using System.Drawing anymore. It may be the case that it could even slow things down.

**Comment by dampee** [comment]
Don't worry (yet).  I'll touch first some simple things by the end of the year.  Just looking around what I can do.  (But too busy right now for customers)

**Comment by JimBobSquarePants** [comment]
This issue was moved to JimBobSquarePants/ImageSharp#2
