### ISSUE TITLE
is it possible to lossless a jpg file ?

### ISSUE THREAD

**Issue by gcmartijn** [JimBobSquarePants/ImageProcessor#180]
I need to upload pictures but first i'm going to resize them, and want to know if I can remove the exif info and to make it lossless.

Like this program does: imageoptim.com

**Comment by JimBobSquarePants** [comment]
This is one of those "read the docs" moments. :wink: 

http://imageprocessor.org/imageprocessor/imagefactory/
http://imageprocessor.org/assets/docs/ImageProcessor.chm

The `ImageFactory` constructor contains a parameter `preserveExifData` which defaults to false. Any further optimization would have to be performed by the programs wrapped by the program you have mentioned. 

https://github.com/JimBobSquarePants/ImageProcessor/blob/c5472548129828ee6095ffd36bd7aa19d56a2ff2/src/ImageProcessor/ImageFactory.cs#L68

Note: By default, ImageProcessor.Web [does not preserve EXIF data](http://imageprocessor.org/imageprocessor-web/configuration/#processingconfig). Post processing optimisation can be performed on processed files using the [ImageProcessor.Web.PostProcessor](https://www.nuget.org/packages/ImageProcessor.Web.PostProcessor/) plugin.

**Comment by gcmartijn** [comment]
Sorry, my question was more about the lossless possibility.
With that I mean this:

http://stackoverflow.com/questions/5451597/how-does-googles-page-speed-lossless-image-compression-work

Maybe its a cool feature for in the future ;)

**Comment by precary** [comment]
Got virus warning on ImageProcessor.chm

**Comment by JimBobSquarePants** [comment]
Thank you @precary but I am going to raise a few points here. 

1. You've provided absolutely no useful information whatsoever in order for me to perform any analysis on your issue. (Antivirus platform etc)
2. You've hijacked a totally unrelated thread to do so. 
3. Windows Defender (if it was that) reports a false positive. It's prudent to check other scanners before reporting. As you can see here 68 tests return a negative virus result. https://www.virustotal.com/en/url/afd26b55100cb2a2f572e2ac30b872b1a7aa498c7b6f66a972014ab07c2b9a7c/analysis/1469085503/

This is altogether considered bad etiquette in the open source community. Please read the provided contribution guidelines so that we may help each other more effectively in the future.

https://github.com/JimBobSquarePants/ImageProcessor/blob/Core/contributing.md

**Comment by precary** [comment]
I'm sorry, you're right, got Spursint.A!cl on Windows Defender looked real
