### ISSUE TITLE
Image compressed when no effect applied.

### ISSUE THREAD

**Issue by sebascomeau** [JimBobSquarePants/ImageProcessor#197]
Image looks compress from original image when I do zero effects on it. Just load and save in the correct image format.

Look this code:

    using (ImageFactory imageFactory = new ImageFactory())
    {
        ISupportedImageFormat format = new JpegFormat { Quality = 100 };

        using (MemoryStream msImage = new MemoryStream(imageData))
        {
            imageFactory.Load(msImage)
                        .Format(format)
                        .Save(imageFileInfo.FullName);
        }
    }

This is the original image:
![webcam-e9b478a9-83e3-4612-ae8a-4182c1ec739e](https://cloud.githubusercontent.com/assets/2814465/8833661/58bc1920-3086-11e5-9ec5-e9bf4a0868c8.jpg)

And this is the result (little bit compress):
![e9b478a9-83e3-4612-ae8a-4182c1ec739e](https://cloud.githubusercontent.com/assets/2814465/8833675/71327ec2-3086-11e5-8445-a53f2768e451.jpg)

The original file size is only 51kb and the result 131kb.

Is there an explaination?

**Comment by JimBobSquarePants** [comment]
I'm not sure what you mean about compressed. 

What I do see is the effects of Gamma adjustment on the image - That can be turned off in the constructor. Bare in mind also that every time a jpeg is re-saved some image quality will usually be lost each time as the image is decompressed and recompressed.

The size is larger because you have set the quality to 100. This adds a lot of colour information in the high frequency range to the image if it is not already there. The recommended value would usually be around 80 - 90.

To find out more, have a read here. It's interesting stuff! https://en.wikipedia.org/wiki/JPEG

**Comment by sebascomeau** [comment]
Compare this area between both picture.

![71327ec2-3086-11e5-8445-a53f2768e451](https://cloud.githubusercontent.com/assets/2814465/8848939/f3855ad0-3111-11e5-8d70-6c24051a29ea.jpg)

And I juste notice that the second picture looks brighter.

**Comment by JimBobSquarePants** [comment]
Did you read what I wrote? Gamma adjustment plus higher frequency range colour information.

**Comment by sebascomeau** [comment]
Yeah, I will try to turn off the the gamma adjustement.

**Comment by sebascomeau** [comment]
Right on!

Turned off the gamma adjustement and let the default quality to 90 of the JpegFormat fix my issues.

Thanks a lot! :)

**Comment by JimBobSquarePants** [comment]
Happy to help :smile:  I have it turned on by default as it ensures correct colour calculation when resizing images or blurring colours.

See this article for a greater insight. It's really good. http://www.4p8.com/eric.brasseur/gamma.html
