### ISSUE TITLE
ImageProcessor.Web.PostProcessor never gets bootstrapped

### ISSUE THREAD

**Issue by chrisfoster78** [JimBobSquarePants/ImageProcessor#200]
PostProcessorBootstrapper.RegisterExecutables never gets called. I have fixed this locally:

- Downloading the source
- Removing the constructor from PostProcessorBootstrapper
- Adding PostProcessorBootstrapper.RegisterExecutables(); to the ApplicationEvents.Start() method

**Comment by JimBobSquarePants** [comment]
Thank you for this but I'm afraid you are incorrect.

The constructor for `PostProcessorBootstrapper` is called since a static class member is referenced by another class.

See the documentation on [MSDN](https://msdn.microsoft.com/en-us/library/k9x6w0hc.aspx)

>A static constructor is used to initialize any static data, or to perform a particular action that needs to be performed once only. It is called automatically before the first instance is created or any static members are referenced.

`PostProcessorBootstrapper` is referenced from the `PostProcessor.RunProcess` method.

    ProcessStartInfo start = new ProcessStartInfo("cmd")
    {
        WindowStyle = ProcessWindowStyle.Hidden,
        WorkingDirectory = PostProcessorBootstrapper.WorkingPath,
        Arguments = GetArguments(sourceFile, targetFile),
        UseShellExecute = false,
        CreateNoWindow = true,
    };

Which is in turn referenced from `PostProcessor.PostProcessImageAsync` and `ApplicationEvents.PostProcessAsync` respectively.

In `ApplicationEvents` there is an assembly level attribute bound to the top of the class. 

    [assembly: PreApplicationStartMethod(typeof(ImageProcessor.Web.PostProcessor.ApplicationEvents), "Start")]

This ensures that the method is called on application start. Phil Haack  describes the functionality of the attribute [here](http://haacked.com/archive/2010/05/16/three-hidden-extensibility-gems-in-asp-net-4.aspx/)

I can attach the debugger to the registration events easily enough which confirms that they are running. I can also navigate to the extracted binaries.

![proof](https://cloud.githubusercontent.com/assets/385879/8956551/fb041f4e-35ee-11e5-90ba-c5c2bfd6ef13.png)

**Comment by chrisfoster78** [comment]
Thanks for the quick response.  Sorry I had assumed it was supposed to be bootstrapped on start-up but you are correct it is working as described. The problem I am having is that it does not appear to be working in combination with AzureBlobCache. At least I think this is the problem but I am also not seeing the exe files in the bin folder on a deployed Azure website. Are you able to confirm that you have had it working well with Azure before I investigate further?

**Comment by JimBobSquarePants** [comment]
Ah... That makes more sense now.

It doesn't work with AzureBlobCache just now. I thought I'd documented as such but I mustn't have.

When I originally wrote the post processor I didn't have Azure support, nor even a pluggable cache system so there's no way to get everything to talk to each other properly.

The way it works is as follows:
 1. Image is processed and cached to disk this image is served to the browser.
 2. The post processing event is fired and this triggers the PostProcessor to copy the cached file to the 
temp folder and attempt to reduce file size.
 3. If the new image is smaller, the new file is copied back over replacing the cached file. Subsequent requests serve the new file.

I originally designed it that way to ensure that a cached file was served as quickly as possible as further optimisation might be slow. The first request missed out on those optimisations but I didn't have a way around that.

Truth be told though I've never benchmarked the speed of the postprocessors  though looking at the benchmarking for jpegs on the link below jpegtran (which would easily be the most commonly used processor out of the bunch) is pretty quick on big images so I don't think it's really an issue.

http://blarg.co.uk/blog/comparison-of-jpeg-lossless-compression-tools

Theoretically I could do it differently and incorporate it into every request by saving the stream to a temp file first, post-processing it then caching it afterwards. I could make it toggleable via settings (probably default to on) so if it becomes a performance issue then we can disable it. 

What do you think?

**Comment by chrisfoster78** [comment]
Personally I wouldn't worry too much about the first ever request being a little slow. Optimising the image may be quicker than resizing it in many cases.

I wrote a simple image handler many years ago and I think the pipeline interface accepted and returned either a byte[] or Stream (can't remember which) rather than an Image to make it a little more flexible and not dependent on System.Drawing. I've been using ImageResizer for the last few years but have recently found this library after using Umbraco. I was very pleased to see a cloud caching plugin which ImageResizer lacks and also the licence is a bonus. I'll raise an issue for now regarding AzureBlobCache and the PostProcessor. I'd be happy to contribute if I can find some spare time outside of work.

Thanks 

Chris
