### ISSUE TITLE
AzureBlobCache and PostProcessor not working together

### ISSUE THREAD

**Issue by chrisfoster78** [JimBobSquarePants/ImageProcessor#201]

**Comment by JimBobSquarePants** [comment]
Well that turned out to be easier than I thought... :smile: 

The pipeline of ImageProcessor.Web is stream based so I was able to intercept that stream and apply the various optimization tools before handing the stream over to the `IImageCache`. **This means that all `IImageCache` implementations will receive the post processed images by default.** This will be enabled by default but can be turned off with additional configuration.

Performance optimizations are as follows:
- Jpeg. Huffman tables optimized losslessly, anything above 10k will re-encoded in progressive format.
- Png. Lossy optimization is attempted first, if the resultant output quality is less than 90% then that output is ignored. All requests are further processed using lossless optimization.
- Gif. comments and extension data are stripped plus maximum optimization is attempted.  

I get between 5-25% additional reduction in file size with my tests with a negligible increase in processing time.

**Note:** Upon release this will render the post processing plugin obsolete.

**Comment by perosb** [comment]
Nugets sonish? ;)

**Comment by JimBobSquarePants** [comment]
Yeah once I've ironed out some other stuff. I'm having to use my phone to have internet just now as I've just moved to Australia and have no broadband.

**Comment by JimBobSquarePants** [comment]
Fixed in [v4.4.0](https://www.nuget.org/packages/ImageProcessor.Web/4.4.0)
