### ISSUE TITLE
Protocol ("http://") is prefixed to path

### ISSUE THREAD

**Issue by janrhansen** [JimBobSquarePants/ImageProcessor#203]
Hi

I've just updated 
ImageProcessor from 2.2.0.0 to 2.2.8.0, 
ImageProcessor.Web from 4.2.1.0 to 4.3.6.0 and 
ImageProcessor.Web.Config from 2.2.0.0 to 2.2.2.0
- and now I have quite a few problems. 

I have an IImageService to serve locally stored files, protected by logins (see #103) where a prefix called "image.axd" is specified AND IsLocalFileService returns true. Previously I would target the service by writing image paths as 
http://customerid.domain.dk/image.axd?id1_id2_id3.jpg?width=120

This will now give me an "Invalid URI: The hostname could not be parsed." asp.net error page. I then noticed that the documentation (http://imageprocessor.org/imageprocessor-web/imageprocessingmodule/#remote) mentions to use 

/remote.axd/your-external-image?width=300
as opposed to 
/remote.axd?http://your-external-image?width=300
- the questionmark and the protocol is missing. 
So I changed my URL to 

http://customerid.domain.dk/image.axd/id1_id2_id3.jpg?width=120

and now I hit the code again. Success! 

However, when the IsValidRequest(string path) method was hit, the path parameter would previously be "id1_id2_id3.jpg", but now it is "http://id1_id2_id3.jpg". Probably because it is a "remote" service? Or why is the protocol suddenly prefixed? This goes for the parameter to GetImage(object id) as well - it is also "http://id1_id2_id3.jpg" now.

Has the recommended way of using the library changed? or is it just a sideeffect of something else. I can just remove the protocol part, but am I doing something wrong?

BTW, may I suggest that you maintain some kind of change-log where you could mention these at times subtle but very important changes to the way things are implemented or are being called etc. That way I wouldn't have to dig around too much... (but could leave you with the work of updating a list when things are released :) 
I know.. more work to you, but it was rather difficult to find out what was wrong here.. maybe because I searched for the wrong terms, but a line with "the syntax has changed from this to that" would have been a good clue :)

Anyway, I hope you can help with this - and thanks for an awesome piece of work!

**Update:**
I removed the protocol part, so now I get a new YSOD:
Invalid file name for file monitoring: 'http://36_82_4e5800df585e4c44af9c5bb7a9aab573.jpg'. Common reasons for failure include:
- The filename is not a valid Win32 file name.
- The filename is not an absolute path.
- The filename contains wildcard characters.
- The file specified is a directory.
- Access denied.

**Update 2:**
So, I kept getting the new YSOD, then tried adding some whitelist items and then it worked. I removed the whitelist items to verify it, and it stil worked. Then I flushed the entire cache folder, and that gave me the YSOD above - but the cached image is still generated on disk. Refresh again, and the cached image is served. Strange. I assume it's an error..... ?
Is that the cache module that fails somehow? 

**Update 3:**
... got another "bright" idea, and removed the 
`<setting key="Protocol" value="http" />`
part of my service settings in security.config. That caused the "http://"-part to disappear from the path and id parameters as mentioned above. Apparently what I was needing, but where are these settings documented, if they are?

**Comment by JimBobSquarePants** [comment]
Ok... So is this your own implementation of `IImageService`?

Why did you have an unneeded setting in your IImageService implementation. Were **you** using it? If not, why include it?  A quick glance at the publically visible code would have indicated its use.

>BTW, may I suggest that you maintain some kind of change-log where you could mention these at times subtle but very important changes to the way things are implemented or are being called etc. That way I wouldn't have to dig around too much... (but could leave you with the work of updating a list when things are released :) 
 I know.. more work to you, but it was rather difficult to find out what was wrong here.. maybe because I searched for the wrong terms, but a line with "the syntax has changed from this to that" would have been a good clue :)

I know you put a smiley on the end of this but this really pisses me off. 

First off, I put a release log on the Nuget package page for every release. 

https://www.nuget.org/packages/ImageProcessor.Web/4.3.0

You could also, if you wanted to, look at the commit history and browse changes.

Secondly and this is a big one. Have you contributed to the documentation? Has anyone really? 

Look at the commit graph for this project. It's embarrassing!

https://github.com/JimBobSquarePants/ImageProcessor/graphs/contributors

This is free software. Free software that costs me precious time to develop and has probably saved your company, and many others, thousands of pounds yet very few developers bother their arse to actually give back. 

Now I get that some people don't because they are afraid that they will make a mistake and doubt their ability but they are, most definitely, a distinct minority.

I'm most probably misdirecting my ager at you, and I apologise if you are upset by my rant but I am very, very tired of putting so much into this project when I get so little back.

**Comment by janrhansen** [comment]
Hi James

To begin with your last sentence, I'm not upset at all and I actually think that I kind of understand how it must feel to put endless hours into a project like this, and not get the community effort back that one could hope for. That is why I put at smiley after my change log "request" - because it would mean more work for you to do, and you probably have a thousand other things to do.

`<self-defence>'
I actually tried to find the information by browsing the source code and looking at commit messages, but I'm completely blank when it comes to git and therefore didn't find the information I was looking for. I hadn't thought about looking at the nuget packages, sorry about that. I can see that "Drops legacy syntax support" is listed for release 4.3.0 - but I probably woundn't have concluded that /image.axd?something was changed to /image.axd/something from that message. Maybe what I really thought about was a more textual explanation of the changes? Something that one knows if one is more involved with the project, because it kind of comes more naturally. A "blog post" of some kind, perhaps?
`</self-defence>'

Yes, it's my own implementation of IImageService, and I think I left the protocol setting there either because it was created by the ImageProcessor.Web.config package, or because it is listed in the documentation (http://imageprocessor.org/imageprocessor-web/configuration/#securityconfig). It was there with 4.2 and it worked, and now it doesn't work, so I have removed it. I probably thought it was there to differentiate between http/https calls or something like that. I'll dig deeper to find out what it actually does.

I know that communicating in writing can lead to misunderstanding - especially as english isn't my first language. So - please - try to read between the lines as well..:
No, I haven't contributed to the documentation, There are two major hurdles for me - 1) learn how to operate git, the formatting etc etc and 2) what could I possibly write about that you haven't already written? 
Regarding 1) - I could spend my time learning it. Admitted.But it IS a hurdle. For me at least.
Regarding 2) - much worse. Take the protocol setting as an example. I don't feel competent enough to read the code, understand what it does and what the intention is, so I would feel that you would have to read and approve everything. But hey, maybe I should just try it. 

Its not that I don't want to help, I just feel like a complete novice using your rather complicated software and as such, yes I doubt my abilities. Yes, your software has probably saved us some amount of money and a lot of time as well, and for that we are very, very thankfull. 

Seriously, I would like to give something back. I'll see if I will succeed in doing that! I'm sorry that I pissed you off, that was definately not the intention - quite the opposite, actually. I hope you will continue your work on ImageProcessor, despite amateurs like me requesting this and that all the time.

Thanks for your time, and I hope we can continue our conversation in a positive "vibe" :)

BR, Jan

**Comment by JimBobSquarePants** [comment]
Hi Jan,

Please accept my apologies for ranting away like I did. It's not cool and definitely goes against the vibe of what I am trying to do online.

v4.3.0 was the version that broke things for you. I had to do some significant rewriting in order to improve the query parser as it was breaking in more and more scenarios. I thought I'd managed to update the system without breaking anything but obviously I missed that. 

I forget sometimes how daunting approaching software like this can be. I've dedicated years of study to be able to get it working and as such I can far too easily assume that everyone knows as much about it all I I do. 

I am looking at a way that I can more easily work with the documentation. Jekyll is no good for me as it doesn't allow people to easily contribute. I may change most of it over to use Github's built in Wiki. That way anyone can edit it easily. 

Anyhow...

I'm glad you got it sorted. If you need anything in the future please don't hesitate to get in touch. I promise I'll be less of a dick next time. 

James
