### ISSUE TITLE
Question regarding ImageProcessingModule, LocalFileImageService and HttpExceptions

### ISSUE THREAD

**Issue by danlister** [JimBobSquarePants/ImageProcessor#277]
Hi James,

Many thanks for your package. It has saved me countless hours of development and I, along with countless other developers, owe you many beers. My issue is more of a question rather an issue. I'll try to explain my scenario as best as I can.

I have an Umbraco site with multiple sites (languages variations). Each site requires their own `apple-touch-icon-precomposed.png` image which can be accessed at the root of each site's domain. My solution for this was to implement a HttpHandler which serves a media item from Umbraco, selected by each site. Therefore, a physical `apple-touch-icon-precomposed.png` file never exists.

My problem is that before the HttpHandler can find and serve the correct image from Umbraco, the ImageProcessingModule runs and tries to find the requested image. As it never exists, the LocalFileImageService [throws a HttpException](https://github.com/JimBobSquarePants/ImageProcessor/blob/V2/src/ImageProcessor.Web/Services/LocalFileImageService.cs#L107). Removing the ImageProcessingModule fixes the issue and allows the HttpHandler to serve the image it finds within Umbraco.

My questions are:

- Do you know of anyway around this issue?
- Should the LocalFileSystemService throw an exception if a physical file cannot be found?
- Should the ImageProcessingModule catch the HttpException from the LocalFileSystemService and ignore any processing to be completed, allowing the request to be executed as normal? Either resulting in a 404 if the file doesn't exist or being served by a HttpHandler.
- Could there be a config setting to determine how missing physical files are handled?

I hope that all makes sense. 

Thanks,
Dan.

**Comment by JimBobSquarePants** [comment]
Hi Dan,

No worries! I'll take you up n that beer offer next time I'm in the northern hemisphere :beers: 

Yeah that all makes sense.

A `HttpHandler` won't help you in this scenario as it is processed far too late in the page lifecycle. ImageProcessor will always beat it to the punch. 

Your scenario is quite special and I would solve it by replacing the `LocalFileImageService` with your own `IImageService` implementation based on it that runs a special case for `touch-icon-precomposed.png` and defaults back to the standard behaviour for other image requests. Basically a copy/paste of the original code plus the logic you have in your `HttpHandler`.

If you install the [configuration package](https://www.nuget.org/packages/ImageProcessor.Web.Config/) you can replace `LocalFileImageService` in the [security.config](http://imageprocessor.org/imageprocessor-web/configuration/#securityconfig) file.

In answer to your question about the thrown exception. The `HttpException` is a 404.

    throw new HttpException((int)HttpStatusCode.NotFound, "No image exists at " + path);

I'm not sure whether the `ImageProcessingModule` should do anything special when that exception is thrown as it could cause unexpected behaviour. As soon as I throw that exception IIS kicks in with its default behaviour and any handling can be dealt with outside of ImageProcessor with whatever you specify in the web.config etc. 

There's no harm however in me (or someone else :wink:) experimenting to see what happens if I handle the error and return out of the HttpModule. My inkling is that it would actually end up with a better workflow in that your handler would be able to take over and 404's etc would also naturally be handled by the application. If that is the case there would be no need for additional configuration.

I'm going to look at reverting the behaviour I added in 4.4.0 that intercepts images with no querystring parameters also as that is causing confusion for some developers.

Hope that is useful

Cheers

James

**Comment by danlister** [comment]
Thanks James for your helpful answer! You beat me to it with regards to the pass through change. For the meantime, I'll install the the config package as you suggested and implement my own `LocalFileImageService`.

**Comment by JimBobSquarePants** [comment]
No worries :smile: 

I should get an update out soonish. Any issues give me a shout.

**Comment by JimBobSquarePants** [comment]
Fixed this in v4.5.0
