### ISSUE TITLE
Memory issues with ImageProcessing.Web 4.4

### ISSUE THREAD

**Issue by HankCFL** [JimBobSquarePants/ImageProcessor#281]
James,
I posted a question about this on the umbraco forums and I am adding clarification specific to ImageProcessing.Web. To isolate the problem I created an empty website and only configured ImageProcessing and added a few thousand images. (IIS 7.5, .net 4.5)

I used a tool to request the images and the memory grows steadily. After all the requests I created a memory dump and there are 8347 System.Web.HttpResponseUnmanagedBufferElement objects on the heap. It looks like it is not the MemCache but the output cache that is the problem.

I'm not sure about this but I think AddFileDependencies in ImageProcessingModule.SetHeaders may be what is triggering asp.net to add the image to the output cache. I wasn't sure what AddFileDependencies did, but I found this https://msdn.microsoft.com/en-us/library/67z4z916%28v=vs.110%29.aspx.

This makes me think the output cache is holding onto the image in unmanaged memory due to a combination of the length the expiration is being set to and the file dependency that is being setup.

Attached is an example of the windbg session for the memory dump.
[mem-debug-session.txt](https://github.com/JimBobSquarePants/ImageProcessor/files/68896/mem-debug-session.txt)

Thanks,
David

**Comment by JimBobSquarePants** [comment]
Hey, thanks for that. Very, very much appreciated!

I'll respond both here and the forums for clarity though i'll be linking to here from there. 

If it's the output cache that is the issue we may have a workaround.

I _think_ it's correct that I am utilizing the output cache plus file dependencies. As far as I understand the mechanism It's allowing much reduced io requests and increased scalability, plus it ensures that if an image changes, the request changes. I think it should be possible for me to cache in the browser though only which might well be better for larger sites.  

I'm not the only person to utilize output caching in this manner though. Imageresizer does so also. https://github.com/imazen/resizer/blob/d987fc27fe2c020cde309620d36158ea3988a963/Core/Caching/ResponseHeaders.cs#L62

If output caching it required for decent performance there are some configuration changes that can be made that should mitigate growth. 

First off it's possible to limit the size of the output cache.

http://www.iis.net/configreference/system.webserver/caching

That is only settable at application level though. According to documentation I have read it defaults to half of available physical memory or available virtual memory whichever is less.

We can also reduce the number of file watchers. There are a lot of DirMonCompletion objects created since I create a lot of folders. Changing the FCN configuration should help.

http://shazwazza.com/post/all-about-aspnet-file-change-notification-fcn/

The largest number of items with the greatest size in your output though is ApplicationImpersonationContext instances. I wonder? Are you using an UNC path in your site? That causes instances to be generated.

http://referencesource.microsoft.com/#System.Web/HttpContext.cs,1113

Cheers 

James

**Comment by HankCFL** [comment]
James,
Thanks for the information.

About the ApplicationImpersonationContext instances. The dump is from a site I created quickly using the local filesystem. My load test script was created for a different site that includes credentials and I forgot to remove them when I reused the script. I think that may be where that is coming from.

Thanks,
David

**Comment by JimBobSquarePants** [comment]
Ah right... No worries,

I'm gonna change the config transforms for the nuget package on the next release to set FCN to "Single". On my test website in the solution that reduced the number of watchers looking out for web.config files from 800+ 

Would it be possible for you to do the same in your test website and report back?

**Comment by HankCFL** [comment]
I just made the FCN change and that dropped the number of DirMonCompletion objects to 5.

**Comment by JimBobSquarePants** [comment]
Ace. That sounds right to me. That should dramatically reduce your memory and process usage.
