### ISSUE TITLE
ImageProcessor.Web Out of the box issues

### ISSUE THREAD

**Issue by capt-caveman** [JimBobSquarePants/ImageProcessor#302]
Out of the box install into Umbraco 7.3.3 doesn't work on shared hosting(Arvixe). All files return as a server 500 response.

Disabling ImageProcessor does allow the images to display again but not without some hiccups in the xml.

After install, the lead <processing> node has two issues: 
'fixGamma'  and  'interceptAllRequests' these attributes cause configuration errors. Removing them allows ImageProcessor to work without taking out the site.

Updating the process node with these remaining attributes works.

<processing preserveExifMetaData="false" postProcess="false">

**Comment by JimBobSquarePants** [comment]
Hi there,

Are you definitely running [ImageProcessor.Web v4.5.0](https://www.nuget.org/packages/ImageProcessor.Web/4.5.0)? The minimum version required for the `interceptAllRequests` value added in [ImageProcessor.Web.Config v2.2.5](https://www.nuget.org/packages/ImageProcessor.Web.Config/2.2.5) is that install.

The issues you are probably having are due to overzealous security configuration on some shared hosting that conflicts with the the version shipped with Umbraco v7.3.3. 

Since Nuget by default specifies the minimum version I can only suggest that you upgrade your installed ImageProcessor>Web to v4.5.0.

Cheers

James
