### ISSUE TITLE
CAIR Plugin

### ISSUE THREAD

**Issue by troyfulton** [JimBobSquarePants/ImageProcessor#320]
Hello,

I'm trying to use the CAIR plugin to do SeamCarving, but I can't find the URL syntax to use...can you please point me to any documentation that you may have regarding using the CAIR plugin.

Thank you.

**Comment by JimBobSquarePants** [comment]
There isn't an ImageProcessor.Web `IWebGraphicsProcessor` implementation for Cair since for many scenarios you require a mask in order to produce decent output. That makes it mostly unsuitable for the web. 

The ImageProcessor extension wraps this software and matches 90% of the API. https://sites.google.com/site/brainrecall/cair

Masks can be generated using https://code.google.com/archive/p/seam-carving-gui/

Unfortunately the docs for the latter seem to have disappeared. 

I hope that proves helpful.

**Comment by troyfulton** [comment]
Hi, Thank you so much for getting back to me.

Ok, so with ImageProcessor, is there a good way to crop an image like this:

http://cornerstone.kyamedia.com/kids.jpg

I know I could use anchor=bottom, and it does a nice job, but we’ll never know what the user might upload…I have another image where faces are in the top 1/3 of the image, so without knowing the anchor position is there a good way to do this via the URL?

 I’m to too savvy with image processing, but from that I gathered, it seemed like seam carving was my best option.  Is there another way with your tools?

Thanks again for getting back to me.

Troy

**Comment by JimBobSquarePants** [comment]
No worries, :smile: 

If you are not concerned with the actual dimensions of the output rather just capturing the are of interest you might get away with using the entropy cropper.

http://imageprocessor.org/imageprocessor-web/imageprocessingmodule/entropycrop/

I keep meaning to add the ability to set minimum dimensions to that plugin but there's always a lot on my plate.

**Comment by troyfulton** [comment]
Ok, thank you.
