### ISSUE TITLE
PNG Resize Blurring even at 100% quality

### ISSUE THREAD

**Issue by ProNotion** [JimBobSquarePants/ImageProcessor#334]
Fantastic project by the way! We have an issue resizing some PNG's on a site which for some reason is causing blurring on the images even at 100%, this is most noticeable on straight lines and text. I've linked to an example,[ the first is the original PNG image](https://drive.google.com/file/d/0BxFLDfbc6Op0Q1o1ZWowM0J0YXM/view?usp=sharing) (566x537) and [the second is the resized version](https://drive.google.com/file/d/0BxFLDfbc6Op0ektrMEs3S0hzT3M/view?usp=sharing) at 560x531 using the following parameters:

`siteplan.png?center=0.44,0.50632911392405067&mode=crop&width=560&quality=100`

[Here is a side by side view of them](https://drive.google.com/file/d/0BxFLDfbc6Op0aDNldzNhTHE0QWM/view?usp=sharing) which shows a bit more clearly the blurring. Is there anything we can do to improve on this and keep the resized image sharp?

Thanks, Simon

**Comment by JimBobSquarePants** [comment]
Hi Simon,

Thanks!

Not with the Framework version I'm afraid. The aspect ratio of your resized image is ever so slightly different which is going to lead to rounding errors. (The downside of pixels). The resampling algorithm used by `System.Drawing` doesn't preserve sharpness as well as some algorithms (Lanczos etc) plus at 8 bits per color component there are always errors at odd ratios so you will inevitably get blurring.

The quality parameter only affects jpeg images not pngs (pngs are a lossless format) so that won't have any affect on the output.  

The Core version I'm building works at 16bit per color component and has vastly better resampling algorithms than `System.Drawing` so in the future we should be able to expect better output.

Sorry I couldn't be more help.

James

**Comment by ProNotion** [comment]
Thanks James for the quick response and detailed explanation. I can at least go back to the designer on the aspect ratio point which might help a little.

Keep up the great work!

**Comment by JimBobSquarePants** [comment]
No worries, happy to help!
