### ISSUE TITLE
Creates border around jpg

### ISSUE THREAD

**Issue by amh2013** [JimBobSquarePants/ImageProcessor#340]
I am getting a top and bottom black border around jpg after resizing

                file.SaveAs(fullpath);
                var size = new Size(imageSettings.ResizeWidth, imageSettings.ResizeHeight);
                var workingImage = imageFactory.Load(fullpath)
                     .Resize(size)
                     .Format(new JpegFormat { Quality = quality });
                workingImage.Save(fullpath);
            }

**Comment by JimBobSquarePants** [comment]
You must be changing the aspect ratio of the image. This by design since jpeg has no alpha channel. You can either maintain the aspect ratio, change the background color, or change to ResizeCrop mode.

Check the options in the documentation

http://imageprocessor.org/imageprocessor/imagefactory/resize/#usage
