### ISSUE TITLE
Richer functionality

### ISSUE THREAD

**Issue by GaryRed** [JimBobSquarePants/ImageProcessor#342]
Looking to extend some functionality - let me know if you find this of interest in including in the core product or you have plans for this.
- Passing position dependent parameters. Many functions take one a single value as a parameter. These functions would be far more useful if you could have a matrix of values, allowing different areas to be processed differently - think stripy multicolored tints, blurring of part of a picture, etc. Thinking of passing a function in rather than an integer or color.
- Iterative generation - an efficient way to generate a number of images, with similar processing rules from one image
- Mask generation - good algorithms for creating masks from images. Either binary, or translucency masks.
- Merging of images using translucency masks
- Additional processes such as area magnification/reduction 
What do you think?

**Comment by JimBobSquarePants** [comment]
Absolutely! As long as we can add everything cleanly, performantly and keep it very simple for the end user I'm more than happy to see these features added.

**Comment by Grebe-M** [comment]
Regarding the "Passing position dependent parameters": I think a clean and common solution for this problem is to allow to set a ROI on the image so only the region covered by the ROI is processed. This is like a (almost free) in-place crop of an image.
For non rectangular shapes a (binary) mask image is passed as an additional argument. The processing function then checks if the corresponding pixel in the mask is zero or greater than zero and skips/processes the pixel in the processed image.

Additionaly: I think one should always be able to pass the kernel size for a (convolution) filter freely and should not be restricted to 3x3, 5x5 or whatever was implemented by hand (e.g. Laplacian 3x3, Laplacian5x5). What if I need Laplacian 13x13?

**Comment by JimBobSquarePants** [comment]
Closing this as there has been no response from the OP. @Grebe-M Will maybe look into arbitrary filter lengths in the future but it's not a priority now. The API is extensible enough for someone to create and use their own processor with the base classes.
