### ISSUE TITLE
Is ImageProcessor (with ImageFactory) and ImageProcessor.Web using same Core ?

### ISSUE THREAD

**Issue by Mtahtaci** [JimBobSquarePants/ImageProcessor#343]
hello , youre doing excellent job here 

i want to ask something about Processor Core

when i use ImageProcessor.Web ( http://xxx.jpg?width=1000&height=500 ) i get more quality image to using ImageFactory.Resize()

i dont really understand is my parameters wrong... i need some help here..

here is the Web Image

![qst001](https://cloud.githubusercontent.com/assets/10106272/13747619/c640d8d4-ea01-11e5-9695-04c552ea9ad8.jpg)

and here is the image that generated by ImageFactory.Resize()

![qst002](https://cloud.githubusercontent.com/assets/10106272/13747640/e30a5ae4-ea01-11e5-8b58-cceef0f5f5f8.jpg)

**Comment by JimBobSquarePants** [comment]
Hi there,

Yes, ImageProcessor.Web uses the `ImageFactory `class underneath to perform all the image manipulation. 

The difference you are seeing is due to a difference in the `ImageFactory `constructor usage.

In the ImageProcessor library the `ImageFactory `class when initialized using the default parameters will adjust the colorspace of the image when resizing to correctly handle gamma adjusted images when resizing and performing other manipulation. In certain circumstances rounding errors due to the limitations of 8 bit color components will cause artifacts to appear in images. This tends to affect darker gradient tones.

In ImageProcessor.Web the `ImageFactory` constructor is initialized with the parameter `fixGamma` set to false. This speeds up processing and prevents images from introduced artifacts during bulk processing.

So in order to generate identical images use the following constructor.

``` c#
// Don't preserve EXIF data, Don't fix gamma
using (ImageFactory imageFactory = new ImageFactory(false, false) {
}
```

Your web querystring parameters are absolutely fine.

I hope that clears things up for you.

Cheers

James

**Comment by Mtahtaci** [comment]
it solved my problem , im very grateful.

if it possible i want to ask another simple question.

when i try to Resize png image (has transparency) , i get an image with removed transparency , 

here is the original image

![wheel](https://cloud.githubusercontent.com/assets/10106272/13749963/33335282-ea0c-11e5-908f-c3ee6019696e.png)

here is the output

![wheel2](https://cloud.githubusercontent.com/assets/10106272/13749971/3e342b16-ea0c-11e5-8dee-d10ace3f5d04.png)

**Comment by JimBobSquarePants** [comment]
Is this using the `ImageFactory`? 

That should not happen, Are you calling the `BackgroundColor` method?

**Comment by Mtahtaci** [comment]
yes , my code is here below

``
ImageFactory imgf = new ImageFactory(false,false);
imgf.Load(s.ToArray()); // s is MemoryStream of Image
imgf.BackgroundColor(Color.FromArgb(255, Color.White));
ResizeLayer rl = new ResizeLayer(new Size(1000, 350),ResizeMode.BoxPad);
imgf.Resize(rl);

**Comment by Mtahtaci** [comment]
i need to add trasnparent border to image (even it has transparency)

**Comment by JimBobSquarePants** [comment]
Well that's why then. 

You are deliberately setting a background color using the `BackGroundColor` method as demonstrated here.

http://imageprocessor.org/imageprocessor/imagefactory/backgroundcolor/

```
imgf.BackgroundColor(Color.FromArgb(255, Color.White));
```

Why are you setting the alpha component of the background color to 255? That is exactly the same as simply using `Color.White`

If you want the png to be transparent you need to not do that.

If an ImageFormat doesn't support transparency (jpeg, 24 bit bmp) then you cannot make the border transparent. You can only set it to an opaque color.

Are you disposing of your `ImageFactory `properly? It doesn't look like you are.

**Comment by Mtahtaci** [comment]
thanks again :) it's solved.

**Comment by JimBobSquarePants** [comment]
No worries, happy to help. :smile:
