### ISSUE TITLE
Unwanted Compression

### ISSUE THREAD

**Issue by crazyhor77** [JimBobSquarePants/ImageProcessor#353]
I have recently been using the Image Processor library for the autorotate function, which works great.  However, I notice the images can sometimes be significantly smaller in size.  My test image is 3mb, but after removing the rotation, it goes down to 1mb.  I have zoomed in on both images and can see the image is being compressed as the quality has dropped.  Even just loading the image and saving it has the same result.  Is it possible to use the library without compression?

```
            using (ImageFactory imageFactory = new ImageFactory())
            {
                imageFactory.Load("test.jpeg")
                    .Save(Directory.GetCurrentDirectory() + "//test2.jpeg");
            }

```

**Comment by JimBobSquarePants** [comment]
Hi there,

Yeah, The default output quality is 90. If you set the quality as specified in the [documentation](http://imageprocessor.org/imageprocessor/imagefactory/quality/) you can set this to 100.

``` c#
using (ImageFactory imageFactory = new ImageFactory())
{
    imageFactory.Load("test.jpeg")
                .Quality(100)
                .Save(Directory.GetCurrentDirectory() + "//test2.jpeg");
}
```

Please bare in mind though that there will always be artifacts generated resaving a Jpeg since it is a lossy format. Also The Jpeg encode in System.Drawing is a bit crummy. 

Cheers

James

**Comment by crazyhor77** [comment]
I think that will be fine.  Thanks for responding so quickly :)

**Comment by JimBobSquarePants** [comment]
No worries, happy to help :smile:
