### ISSUE TITLE
Rebracer

### ISSUE THREAD

**Issue by cartman300** [JimBobSquarePants/ImageProcessor#390]
It would be nice if the creator added a [rebracer](https://visualstudiogallery.msdn.microsoft.com/410e9b9f-65f3-4495-b68e-15567e543c58) file to the solution, it would give some consistency because my VS is configured to use tabs and put braces on the same line (instead of new line). Currently i can't use auto indent because it would change the whole opened file with my own style.

**Comment by JimBobSquarePants** [comment]
I didn't know about this tool. An excellent idea!

**Comment by Jeavon** [comment]
.editorconfig file too please :) http://editorconfig.org/

**Comment by JimBobSquarePants** [comment]
@Jeavon How does that one work? Do I have to save the settings manually?

**Comment by Jeavon** [comment]
@JimBobSquarePants you just add a .editorconfig to the root of the project, then any IDE (VS or otherwise) that has the EditorConfig plugin installed will obey the rules. We have it installed in VS and Sublime so C# devs and front enders are all using the same space style for example.
e.g. https://github.com/CrumpledDog/Umbraco-AzureCDNToolkit/blob/develop/.editorconfig

**Comment by JimBobSquarePants** [comment]
Yeah but do I have to manually write those settings or can I export them from visual studio?

**Comment by Jeavon** [comment]
Yes you do need to create it (or copy it from an existing one)

**Comment by JimBobSquarePants** [comment]
Cool. I'll have look, just wanna make sure I do it correctly.
