### ISSUE TITLE
[framework] ImageProcessorBootstrapper not finding WebP plugin

### ISSUE THREAD

**Issue by scottgerring** [JimBobSquarePants/ImageProcessor#422]
Hi,

I've got a simple asnet5 web app set up, and have been using ImageProcessor to convert from PNG to WebP on the fly - which works great!

When I try and convert the other way around - read WebP and output PNG - I get unsupported format exception:

```
Input stream is not a supported format.
```

It looks like **ImageProcessorBootstrapper** is failing to discover the WebP plugin when it is initialised, returning only the built-in formats. I've wrapped my use of ImageProcessor into a class stored in an aspnet5 assembly, which references ImageProcessor as follows:

```
 "dependencies": {
    "ImageProcessor": "2.4.1",
    "ImageProcessor.Plugins.WebP": "1.0.5",
    "Microsoft.AspNet.Mvc.Core": "6.0.0-rc1-final"
  }
```

Outside of that, I pull my library into a unit test assembly, and a mvc6 web app; in both contexts, the bootstrapper fails to discover WebP. Significantly, I can use reflection to prod the bootstrapper and jam the WebP plugin into ```SupportedImageFormats```, and everything works happily - however this is obviously not a great approach!

I've had a look at the source, and it seems like there is no way to provide the bootstrapper with extra formatters, if its enumeration of the available assemblies doesn't yield everything we're looking for. It is difficult to replace the behaviour of the bootstrapper without modifying the library, as it is pulled statically into the processor. 

Is there some workaround for this that i'm missing, or a mechanism to modify the formatter bootstrap process?

Thanks,

Scott.

**Comment by JimBobSquarePants** [comment]
Hi Scott,

First off I'd like to say I'm really recommending developers **not to use the ImageProcessor Framework library on Asp.NET Core based projects**. There's simply too many unknowns to cater for and I am writing the **ImageProcessorCore** library to specifically cater for that environment. 

The failing is most likely due to a change in how binaries are stored within a Asp.Core based application. I've not looked into the details at all for how it works now.

So to answer your question. No, there is no existing mechanism that will allow you to add new formats outwith the automated TypeFinder. If you want to write a means to do so, please go ahead and submit a PR as that would probably allow a fix for #420 also. I unfortunately have a very full plate just now with the new library so adding new features is not currently possible for me to do but I am happy to review and accept any solution you have.

Cheers

James

**Comment by JimBobSquarePants** [comment]
I've added a new method which allows statically adding image formats for your scenario. This will be in the next release which I will release asap.

``` c#
ImageProcessorBootstrapper.Instance.AddImageFormats( new BitmapFormat(), new GifFormat());
```

**Comment by JimBobSquarePants** [comment]
New release available on Nuget now.

**Comment by scottgerring** [comment]
This is great, thanks! Pulling now.

**Comment by JimBobSquarePants** [comment]
Good luck!

**Comment by glat** [comment]
I had to use that method because I recompiled ImageProcessor with strong name to put in cache but the line is wrong. It does nothing because ToList() creates a clone of the object so the line:

this.SupportedImageFormats.ToList().AddRange(format);

should be:

List<ISupportedImageFormat> list = this.SupportedImageFormats.ToList();
list.AddRange(format);
this.SupportedImageFormats = list;

Please try to let LoadSupportedImageFormats() load at least the internal formats without checking for assembly reference, or let it know about assembly in GAC.

Kind regards

**Comment by JimBobSquarePants** [comment]
Could you perhaps create a PR?

**Comment by JimBobSquarePants** [comment]
Just pushed a fix, will be in next deploy
