### ISSUE TITLE
Unsure what to include (newbie)

### ISSUE THREAD

**Issue by nueverest** [JimBobSquarePants/ImageProcessor#423]
What using statement(s) do I need to get the correct `Image` class?

I can't seem to get this code from the readme working.

    Image image = new Image(stream);
    image.Resize(image.Width / 2, image.Height / 2)
         .Greyscale()
         .Save(output);

I tried `using System.Drawing` but that didn't work.  It must be something simple, but I just don't know what to try.

**Comment by nueverest** [comment]
I found another way by modifying the example in the [documentation](http://imageprocessor.org/imageprocessor/imagefactory/), and sleuthing out the correct using-statements.  Maybe it will help others. This will save the resized image to disk which is my basic use case.

    using System.IO;
    using ImageProcessor;
    using System.Drawing; 
    
    string input_file = @"C:\path\to\image.png";  
    string output_file = @"C:\path\to\image-resized.png";

    byte[] photoBytes = File.ReadAllBytes(input_file);
    // Format is automatically detected though can be changed.
    Size size = new Size(45, 45);
    using (MemoryStream inStream = new MemoryStream(photoBytes))
    {
        using (MemoryStream outStream = new MemoryStream())
        {
            // Initialize the ImageFactory using the overload to preserve EXIF metadata.
            using (ImageFactory imageFactory = new ImageFactory(preserveExifData:true))
            {
                // Load, resize, set the format and quality and save an image.
                imageFactory.Load(inStream)
                            .Resize(size)
                            .Save(outStream);
            }
            // Save resized image to disk.
            using (var fileStream = File.Create(output_file))
            {
                outStream.WriteTo(fileStream);
            }
        }
    }

**Comment by JimBobSquarePants** [comment]
Hi @nueverest, Welcome and I'm glad you solved your issue!

I can imagine that there is a lot to take in when looking at the library for the first time.

The first code example you listed when opening the issue is specific to the new **ImageProcessorCore** library as specified in the readme. The second example from the website is from the **ImageProcessor** Framework library.

I've tried to make the readme in each branch as clear as I can and each library has a different name but I haven't had the opportunity to write new, much improved, documentation to make things more clear. There is a lot of work planned though to create first class documentation. 

If you have any further questions please visit the [chatroom](https://gitter.im/JimBobSquarePants/ImageProcessor) on Gitter and I'll try to help you out.
