### ISSUE TITLE
Memory Leak in Image Resizing

### ISSUE THREAD

**Issue by crohkohl** [JimBobSquarePants/ImageProcessor#429]
Hi,

I am using the latest version and there seems to be a memory leak. I think it was also present in the previous versions. My Code is as follows:

```csharp
byte[] imData = ...;

using (var imf = new ImageFactory(preserveExifData: false))
{
    imf.Load(imData);
    imf.Format(new JpegFormat() { Quality = 70 }).Resize(new ResizeLayer(new System.Drawing.Size(200, 200), ResizeMode.Crop, AnchorPosition.Center, true));
    imf.Save(fnameSmall);
}

```

This piece of code runs several thousand times and leaks memory until we are out of memory.

Any idea?

I will try to debug the library myself but any help would be appreciated.

**Comment by JimBobSquarePants** [comment]
Hi there,

No, I've not noticed any leaks myself as I'm always careful to clean up after each method. Youre the first to report anything also.

Since we are only calling 4 methods involving the image itself: `Load`, `Copy (internal)`, `Resize`, and `Save`. That's where to look. Have you any idea how much is lost on each iteration?

I'm assuming you have already ran the rest  of the code without ImageProcessor to ensure there are no leaks elsewhere?

**Comment by crohkohl** [comment]
Shame on me. My Parallel task scheduler was spinning out of control and slowly created more and more threads. That was in my test program aswell. As soon as I limited the number of threads the memory usage was a flat line. Keep up the great work :+1:  and sorry for the false alarm.

**Comment by JimBobSquarePants** [comment]
That's a sweet relief! Thanks for double checking!
