### ISSUE TITLE
Issue with Overlay - Image Processor

### ISSUE THREAD

**Issue by simoazzo** [JimBobSquarePants/ImageProcessor#445]
Hi Guys,

Can anyone give some insight about this:

I am trying to set a watermark like this: `http://auctions.remax-malta.com//media/85370/a001l06-1-main.jpg?anchor=center&mode=crop&width=500&height=500&overlay=wm.png&overlay.opacity=80`

The above works.

But then, if I try to exact url but change the width or height, not works:

`http://auctions.remax-malta.com//media/85370/a001l06-1-main.jpg?anchor=center&mode=crop&width=700&height=500&overlay=wm.png&overlay.opacity=80`

May be something with caching or something?

Can anyone guide me on this?

Thank you

Kind Regards

**Comment by JimBobSquarePants** [comment]
Hi there, 

Is this the same issue as #438? If so, please do not create duplicate issues. 

This is **not** the Watermark plugin, this is the Overlay plugin and you have not provided the information as specified in the [contribution guidelines](https://github.com/JimBobSquarePants/ImageProcessor/blob/2acf4fe804efd492297eab966fb5202502ea5455/contributing.md). 

Now, to the problem.

Debugging your issue by trimming the url to only include the overlay syntax.

```
http://auctions.remax-malta.com//media/85370/a001l06-1-main.jpg?overlay=wm.png&overlay.opacity=80
```

Throws the following error:

>The request /media/85370/a001l06-1-main.jpg?overlay=wm.png&overlay.opacity=80 could not be understood by the server due to malformed syntax.

This is thrown because the overlay plugin has not been enabled in your configuration. Earlier cached versions are working because you were either using a version that allowed all plugins to run (which was a security concern for many) or you have changed your configuration.

All this behavior is clearly documented and I strongly recommend you read the documentation thoroughly before continuing.

http://imageprocessor.org/imageprocessor-web/

Note: once the plugin is enabled you will have to clear your cache in order to view the new images.

James
