### ISSUE TITLE
Use ImageProcessor in .NETCore 1 Projects

### ISSUE THREAD

**Issue by amirzandi** [JimBobSquarePants/ImageProcessor#447]
Hello,

Would you please guide me how to use your package in a .NETCore Project?

Thanks.

**Comment by JimBobSquarePants** [comment]
Hi there, 

As specified in the [Readme](https://github.com/JimBobSquarePants/ImageProcessor/tree/93be57e7c664506115d8dcb098fd6f404f201332#thankyou-for-reading-this) the Core package is alpha which means that it shouldn't be used in a production environment. 

If you wish to evaluated the library though you can download the latest build package from the [MyGet package repository](https://www.myget.org/gallery/imageprocessor).

**Comment by amirzandi** [comment]
My question was something different. I just want to see how it works in a DotNetCore project. How can I import required files into a DotNetCore project!
Please guide me on this issue.

**Comment by JimBobSquarePants** [comment]
Using Myget as described is the only way to use the library in a DotNetCore project. If you need guidance on that I suggest you read the Microsoft documentation available online

**Comment by amirzandi** [comment]
the ImageFactory class is not available while I did get clone.... what should I do?!

**Comment by amirzandi** [comment]
Please help!

**Comment by JimBobSquarePants** [comment]
ImageFactory does not work in DotNetCore because System.Drawing is not part of DotNetCore. That is why there are two libraries - ImageProcessor and ImageProcessorCore. 

This is all in the readme.

**Comment by amirzandi** [comment]
Dear Jim,
I eventually find out how to import your code into my project. The problem is that, I store image in Database and I need the Image to be converted to the Byte[] and I do that as follow:
MemoryStream st = new MemoryStream();
                    using (Stream file = image_data.OpenReadStream())
                    {
                        Image img = new Image(file);
                        img.Resize(400, 400);
                        img.Save(st);
                    }
                    byte[] b = new byte[st.Length];
                    st.Read(b, 0, (int)st.Length);
                    qe.image = b;
                    qe.image_name = image_data.FileName.ToString();
                    qe.image_type = image_data.ContentType.ToString();

The store procedure is working fine but the display procedure is not work. If I do not use your code and store the original version, it works fine.

Would you please help me on this matter?

**Comment by JimBobSquarePants** [comment]
Hi Amirzandi,

The issue tracker is not the place for questions, we have a [Gitter](https://gitter.im/JimBobSquarePants/ImageProcessor) channel for that. Have you read the [contribution guidelines](https://github.com/JimBobSquarePants/ImageProcessor/blob/8b46a446f62b80bcf284d1532a8f88448c260721/contributing.md)? This stuff is important.

That said, what is wrong with the [MemoryStream.ToArray()](https://msdn.microsoft.com/en-us/library/system.io.memorystream.toarray(v=vs.110).aspx) method?

Also, don't store images in databases in that manner; it's a terrible idea, use the Filestream database type and store a pointer to an image stored in the filesystem or better yet use some sort of blob storage mechanism.

**Comment by amirzandi** [comment]
Ok thanks. I will share my problem via Gitter.im website and especially in your room.

Bests.

**Comment by Ciantic** [comment]
I think the problem is that it doesn't work with netcoreapp1.0, this app requires net46 or similar framework. Is this intentional? If the library targets only net45/net46 it can't be run in .NET Core only environments such as Linux.

It would be nice if it worked with this kind of project.json:

```

  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0"
        }
      }
    }
  },
```

But in order to do this, the library must shake it's dependency on System.Drawing, which is being deprecated in .NET Core.

**Comment by JimBobSquarePants** [comment]
What dependency on `System.Drawing`?

Have you tested any of this?

I've just downloaded the latest nightly from the [MyGet](https://www.myget.org/gallery/imageprocessor) repository and installed it successfully into a .NET Core console application. Everything built perfectly.

Here's the resultant project.json

``` javascript
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "ImageProcessorCore": "1.0.0-alpha1039",
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0"
    }
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  }
}
```

And here's a screenshot of the running console.

![sample](https://cloud.githubusercontent.com/assets/385879/18509595/ae7cff88-7abc-11e6-8c8f-419526c97be7.png)

**Comment by Ciantic** [comment]
@JimBobSquarePants sure I tested, not trolling, honest.

I think this might be the problem: If you start typing in Visual Studio to project.json "ImageProce..." it suggests this:
```
    "ImageProcessor": "2.4.4",
```

Naturally I chose that, I gather that is wrong? Also, I thought I was right because I read your benchmark project.json as an example: https://github.com/JimBobSquarePants/ImageProcessor/blob/Core/tests/ImageProcessorCore.Benchmarks/project.json which uses net461, and thought I did everthing right.

I see in your example that it should be `"ImageProcessorCore": "1.0.0-alpha1039",` will try with that.

**Comment by JimBobSquarePants** [comment]
Do you have the MyGet feed in your package manager settings? I always rely on Nuget Package Manager to install dependencies. 

The benchmark project.json is set up like that because I am benchmarking against System.Drawing which requires the full .NET framework 

ImageProcessor and ImageProcessorCore are two separate products. One that I now consider legacy which requires the full .NET Framework and relies on System.Drawing and the new one (Core) which has no dependencies outwith the basics.

**Comment by Ciantic** [comment]
Yes, got it working now with bleeding edge NuGet feed. Excellent library! Thanks.

**Comment by JimBobSquarePants** [comment]
Excellent. Have fun and please any feedback let me know.
