### ISSUE TITLE
Is it possible to position the Watermark text to the bottom of an image?

### ISSUE THREAD

**Issue by protherj** [JimBobSquarePants/ImageProcessor#452]
The position of the text watermark appears to be in pixels.  It is possible to have the position by a percentage unit to allow for putting the image on the bottom?

Thanks,
Jason

**Comment by JimBobSquarePants** [comment]
Hi Jason,

Out of the box no, I suppose you could calculate it though given the size of the image. 

I'm assuming that you are using ImageProcessor.Web so that would require creating an alternative Watermark processor based on the current.

This wouldn't be high on my list of priorities just now but I'd be happy to accept a PR if you fancy giving it a go?

Cheers

James
