### ISSUE TITLE
Version 2.0.1 faster than 2.1.0+

### ISSUE THREAD

**Issue by rodrivel** [JimBobSquarePants/ImageProcessor#455]
Hi!
We started using ImageProcessor 2 years ago, version 2.0.1.0 with net framework 4.0.  Now, as we need to add an overlay to images we've been forced to update from version 2.0.1 to at least 2.1.0 which started including this functionality. 

Since then, we have noticed than the same processing takes about nine or ten times longer. With "same processing" I refer to cropping, resizing and adding some filters, same tasks that before, without adding the overlay yet.

Any suggestions? Thanks in advance.

**Comment by JimBobSquarePants** [comment]
@rodrivel 

First question? What version are you actually using and if it's not the latest? (v2.4.4) Why not?

9 or 10 times slower is a lot. Do you have benchmarks to back that up?

There's a lot more going on inside the ImageFactory class now than there used to be to sanitise input and ensure that data is correctly stored but if anything the latest version should be much faster since I did a lot of work recently to reduce memory usage and reduce copying of information.

Two years is a long time to not update your references simply from a security perspective and .NET 4.0 is not supported by MS anymore.

**Comment by rodrivel** [comment]
@JimBobSquarePants we tried to update to v.2.4.4 and noticed that in our case, it was less performant so we went back to v2.0.1. 

I don´t have a benchmark that can analyse only ImageProcessor performance, but we have been measuring the time it takes for a user to upload an advertisement (which involves all ImageProcessor tasks mentioned before), tried with both versions in same enviroment conditions repeatedly and in average it took about 35s (v2.4.4) when it used to take 4s.

Finally, I know we don´t follow best practices in many cases. Updating references and documenting are some of those :disappointed:

**Comment by JimBobSquarePants** [comment]
Wow! 35 seconds?

How big are the images? Are you still on .NET 4?

Could you do me a huge favour and upload a demo image and code sample so I can see if I can replicate? My laptop is about as slow as it gets so we should be able to see if there is s a problem.

Cheers!

**Comment by rodrivel** [comment]
@JimBobSquarePants, we have been making some changes and updates and it seems to work perfect now (v2.4.4 with .NET 4.5).  The whole process takes 600ms for each image (jpg 1200x900px).

Sorry for the late and thanks for your time.

Best

**Comment by JimBobSquarePants** [comment]
That's great news! You had me worried there!
