### ISSUE TITLE
The specified CGI application encountered an error and the server terminated the process

### ISSUE THREAD

**Issue by Bartmax** [JimBobSquarePants/ImageProcessor#467]
When resizing multiple big images on aspnet core i usually get:
``` 
The specified CGI application encountered an error and the server terminated the process
```

is there anything I can do to mitigate this?

**Comment by JimBobSquarePants** [comment]
No idea. I'm going to need waaaaay more information than that.

**Comment by Bartmax** [comment]
What kind of information?
This happens on azure standard-size machine. It doesn't on local machine, and I can repro if I choose to resize ~7 images of about ~20mb each to a resolution of 600px width (keeping aspect) that ends in about ~45kb. (just an example). Almost any time consuming resize process return that error.

**Comment by JimBobSquarePants** [comment]
Are those images 20MB each compressed or do you mean in memory?
How long are they individually taking?

If the resize is actually taking place then you might be on track. It sounds like there is some sort of response timeout taking place which would be in the realms of the ASP team to instruct you on working around. It can't be an imageprocessor specific issue since no exceptions are thrown by the library and we are successfully encoding.

I haven't actually used ASP.NET Core yet so I'm not going to be much help I'm afraid.

**Comment by Bartmax** [comment]
@JimBobSquarePants 20mb compressed.
Each image takes a considerable amount of time. don't know exactly how much
I will try to investigate a little further and then cross reference to the aspnet team.
I'll let you know if I discover something.

**Comment by JimBobSquarePants** [comment]
Thanks!

**Comment by JimBobSquarePants** [comment]
This issue was moved to JimBobSquarePants/ImageSharp#13
