### ISSUE TITLE
How can I reduce the depth when saving [question] [core]

### ISSUE THREAD

**Issue by dwdickens** [JimBobSquarePants/ImageProcessor#469]
Hi! Love this project and thanks so much for all the work in creating it.

I'm using ImageProcessorCore to resize and save uploaded images. However, sometimes the image size is large (both the uploaded image and saved image). For example, the attachment is a 308kb PNG that is only 376x468.

I think this is because of the bit depth (32)? If so, how can I cap this when saving the image so that the file size is reduced?
![707](https://cloud.githubusercontent.com/assets/13432550/18275210/545e7b32-7489-11e6-8472-2500391fa1ee.png)

**Comment by JimBobSquarePants** [comment]
Hi there and thanks! There's a couple ways just now.

If you want to preserve the original image format as png, setting the `Image.Quality` property to 256 and below will automatically quantize the image encoding an indexed version. The Wu Quantizer is very good and will work well for most pngs. 

Otherwise you can save the image using the `Save(Stream, IImageEncoder )` overload and use a new `PngEncoder` instance with the `PngColorType` property set to `PngColorType.Rgb`

    image.Save(stream, new PngEncoder { PngColorType = PngColorType.Rgb });

Hope that helps

James
