### ISSUE TITLE
Processing dynamic MVC FileContentResult images

### ISSUE THREAD

**Issue by DanDiplo** [JimBobSquarePants/ImageProcessor#476]
This is more of a query than an issue and pertains to ImageProcessor.Web 4.6.4. I'm experimenting with an  MVC 5 application that stores images in the database and then returns them to the view as a [FileContentResult ](https://msdn.microsoft.com/en-us/library/system.web.mvc.filecontentresult(v=vs.118).aspx) using an MVC Controller.  The experiment is based on this tutorial - [ASP.NET MVC 5 with EF 6 - Working With Files](http://www.mikesdotnetting.com/article/259/asp-net-mvc-5-with-ef-6-working-with-files) (You can download the source code from the article).

My issue/query is that ImageProcessor isn't intercepting these results and so won't process them. It works fine with images served from filestore. So, for example, the following URL that calls a controller and returns a JPEG as a `FileContentResult`:

`http://localhost:1234/File?id=1`

If I append query string params to it, such as:

`http://localhost:1234/File?id=1&width=20`

then it is not resized. 

The controller is returning the correct content-type in the response, which is:

```
Cache-Control:private
Content-Length:19594
Content-Type:image/jpeg
Date:Wed, 21 Sep 2016 12:46:29 GMT
Server:Microsoft-IIS/10.0
X-AspNet-Version:4.0.30319
X-AspNetMvc-Version:5.2
X-Powered-By:ASP.NET
```
Is there any way to get this working so that these type of dynamic images can be processed? I realise you are a busy man, so don't feel obliged to answer if you don't have time.

**Comment by JimBobSquarePants** [comment]
Hi Dan,

Yeah, ImageProcessor.Web won't be able to intercept images that way since it will be expecting the file to be on the filesystem.

What you will need to do is create an implementation of the `IImageService` that ImageProcessor.Web can then use to intercept the request and pull the resultant stream from the database.

Here's a demo implementation that will get you started.

https://github.com/JimBobSquarePants/ImageProcessor/blob/1daf15cb83cd7b715192260acfdf76aca8dc3b9f/tests/ImageProcessor.TestWebsite/ImageServices/DatabaseImageService.cs

After implementing the interface you need to add the service to your site via the config. Here's a demo config in the same test website.

https://github.com/JimBobSquarePants/ImageProcessor/blob/1daf15cb83cd7b715192260acfdf76aca8dc3b9f/tests/ImageProcessor.TestWebsite/config/imageprocessor/security.config

I hope that's all clear.

Cheers

James

**Comment by DanDiplo** [comment]
Thanks, James, that's a great answer and points me on the right track!

**Comment by JimBobSquarePants** [comment]
Excellent. I'll close this for now then. If you get into any difficulty please reopen the issue and we can figure it out together.
