### ISSUE TITLE
Error from ImageProcessor with CKEditor's icons.png

### ISSUE THREAD

**Issue by dsargent3220** [JimBobSquarePants/ImageProcessor#477]
We upgraded to a newer version of ImageProcessor and now CKEditor's icons.png causes it to break anytime we pass a querystring to it (any querystring)
I'm attaching the specific file.  Took us a while to find it because an older copy of ImageProcessor has already cached it on prod and some of our local boxes, so it seemed intermittent.
Anyway, here's the file.
![icons](https://cloud.githubusercontent.com/assets/3372486/18718264/b46cc39a-7fd7-11e6-97bf-45a34c0f033f.png)

**Comment by JimBobSquarePants** [comment]
Hi Dave,

Could you perhaps please provide me with a little more information?

Specifically:

- What versions of ImageProcessor and ImageProcessor.Web you are using?
- What is the exception message?
- What would be a demo querystring parameter?

I'm fairly certain the image is irrelevant and the issue is one of security and that your custom querystring parameters are throwing the error.

See the documentation here for details as to why.

http://imageprocessor.org/imageprocessor-web/

If so, implementing this eventhandler correctly will probably solve your issues.

http://imageprocessor.org/imageprocessor-web/imageprocessingmodule/#events

Hope that helps

Cheers

James

**Comment by dsargent3220** [comment]
I'm at home but will do my best. 
Latest versions of both (not the core rewrite)
I'm trying to remember the exact message. It was coming from image processor.web. Something about not understanding the attribute. Sorry. All I can recall right now. 
Any query string. ?a would do it. Creditor automatically adds cachebusting querystrings to their assets, this the problem. 
I'll get you the exact error message tomorrow morning.

**Comment by JimBobSquarePants** [comment]
Yeah, that sounds exactly like the issue I've described. We had to do some quite draconian work in order to beef up the security. implementing the event-handler to strip out the params internally will be what you want.

**Comment by dsargent3220** [comment]
Got this implemented and it worked.  Thanks!

**Comment by JimBobSquarePants** [comment]
Great Stuff! 😄
