### ISSUE TITLE
Poor quality when resizing images on core

### ISSUE THREAD

**Issue by gdoron** [JimBobSquarePants/ImageProcessor#483]
Hi, 

We heavily use ImageProcessorCore on [yooocan.com](https://yooocan.com) and usually it works very well, but sometimes the images quality is significantly downgrades.
For example, we have this image:
![screen shot 2016-09-27 at 11 51 13](https://cloud.githubusercontent.com/assets/6141009/18869113/8ac14d78-84b3-11e6-8afe-4ef48e6a4e11.png)
Which is in a decent  quality, but when resized with ImageProcessor it becomes:
![image](https://cloud.githubusercontent.com/assets/6141009/18869168/cc1991fe-84b3-11e6-9502-27f828c90673.png)

The code we are using is:

	var image = new Image(stream)
                        {
                            Quality = quality // 0.9
                        };

            var options = new ResizeOptions
                          {
                              Size = new Size(Math.Min(554, image.Width), Math.Min(554, image.Height)),
                              Mode = ResizeMode.Crop
                          };

            var output = new MemoryStream();
            image.Resize(options)
                .AutoOrient()
                .Save(output);
            output.Position = 0;
            return output;
            
You can see some more examples on our website: https://yooocan.com/Story/263/VARIETYS-PEACEABLE-KINGDOM.

version: "ImageProcessorCore": "1.0.0-alpha-1021"

Thanks!
Doron

**Comment by gdoron** [comment]
I noticed I forgot to ask a question...
Do we do something wrong in the code? or is it a bug/limitation in the library itself?

Also, thanks a lot @JimBobSquarePants! your amazing library really helps us to empower people with disabilities!

**Comment by JimBobSquarePants** [comment]
Hi Doron,

Thanks! I'm so glad my work is helpful.

The behaviour you are seeing is by design. 

You're changing the quality of a png image. If the quality is 256 or less for that format, then the image is quantized and saved as an indexed png with the quality value representing the number of colors in the palette. 

The behaviour for each format is as follows.

First Format | Quality Range | Result
------------ | -------------|-------------
Jpeg | 1-100 | At quality < 80 the jpeg switches to subsampling mode of 4:2:0 to reduce filesize
Gif | 1-256 | Each value represents the number of colors to use in the palette.
Png | 1-int.MaxValue | If quality <= 256 then each value represents the number of colors to use in the palette.
Bmp | 1-int.MaxValue | No effect.

I'll have this all documented eventually but since I'm only still in alpha (tut, tut using this in a production environment btw) I haven't started writing any documentation yet.

Hope that helps

Cheers

James

**Comment by JimBobSquarePants** [comment]
Oh, meant to say. later alphas reset the stream so you don't have to anymore.

**Comment by gdoron** [comment]
Thanks @JimBobSquarePants for the rapid response!
I understand the issue now, but I still don't understand two things:

1. What happens if the `Quality` is > 256 for a png image?
2. I want to reduce the size of the image by 10% (random number I picked in case you ask...) whether it's a png or a jpeg image, what's the way of doing it?

Thanks for the tip with reset the stream, I wasn't aware of it.

Doron

**Comment by JimBobSquarePants** [comment]
No worries 😄 

1. The image is encoded in 32 bit mode unless you explicitly use the `PngEncoder` to save the image with the  `ColorType` property set to `PngColorType .Rgb`. That would reduce the filesize by a bit if you don't require transparency.

2. Reducing the filesize by a percentage isn't something you can consistently do since image compression ratio depends on may factors, colour palette, colour distribution, alignment, etc. The best bet is to save your images as jpegs at 80% and have a look at the output. 

Jpegs are always the best choice when is comes to saving photos. The compression algorithms take advantage of the way we see colours much better than any other format and you will always produce a smaller image than png for anything other than block colours.

**Comment by gdoron** [comment]
**Thanks James**. 👍 
I changed to saving `.SaveAsJpeg(output, 80);` as you suggested and it works **very well**.

BTW, IMHO I think having a property `Quality` which sometimes, depends on the image format-encoder, doing other things is a bad design.

Best,
Doron
The [yooocan](https://yooocan.com) family 😄

**Comment by JimBobSquarePants** [comment]
> BTW, IMHO I think having a property Quality which sometimes, depends on the image format-encoder, doing other things is a bad design.

You might well be right on that one. I'll have a good rethink.
