### ISSUE TITLE
Calculation bug in Constrain()

### ISSUE THREAD

**Issue by Trothir** [JimBobSquarePants/ImageProcessor#484]
For testing purposes I generate various blank images with random width and height. After that the image is loaded and resized (via Constrain) to 16x16. Some dimension however aren't resized.

Some examples before and after factory.Constrain(new Size(16, 16)):
- 363x12787 to 363x12787
- 61x5353 to 61x5353
- 3916x107 to 3916x107
- 7239x180 to 7239x180
- 27x6974 to 27x6974
- 6929x207 to 6929x207
- 9821x294 to 9821x294
- 9941x11 to 9941x11
- 134x5752 to 134x5752
- 59x7106 to 59x7106
- 2567x44 to 2567x44
- 260x8589 to 260x8589
- 3992x12 to 3992x12
- 228x7455 to 228x7455
- 45x4986 to 45x4986

Maybe there are some rounding issues?

**Comment by JimBobSquarePants** [comment]
Hi @Trothir,

I'd like to highlight  first the method description for `Constrain`.

>Constrains the current image, resizing it to fit within the given dimensions whilst keeping its aspect ratio.

http://imageprocessor.org/imageprocessor/imagefactory/constrain/

Looking at the image sizes you have provided I'd say this bug is human in origin. I'm not sure how you expected to get a viable result. 

Let's have a look at one of your ratios and do the calculation. I've picked one which has a smaller difference in ratio.

**363x12787**

Since the longer dimension is known to be **16** If I want to figure out the correct size for the shorter dimension I do it as follows.

```
w = (363 / 12787) * 16
```

That dimension will have to be an `int` so in code. 

``` c#
// We use Convert to round up from .5 as casting truncates
int w = Convert.ToInt32(((double)363 / 12787) * 16); 
```

There's only one answer to logically expect there and it is zero **0** since the double that is being converted is less than **0.5** at **0.454211308360053**.

When ImageProcessor encounters a zero dimension, rather than throw it simply returns the original source. (Whether it should do that is contentious, personally I would now throw but I cannot now change expected results in such a massive way)

As you should now be able to see there is no rounding error and the method is operating exactly as described. 

I hope that clears things up for you.

Cheers

James

**Comment by Trothir** [comment]
First of all thanks for your detailed answer!

Of course, you're totally right, but Constrain() should always force the desired size.
To create a valid image within the restrictions I suggest to limit the lower bound
simply to 1 pixel. 

Maybe a Math.Min could fix it?

`int w = Convert.ToInt32( Math.Min(1.0, ((double)363 / 12787) * 16) );`



(BTW, nice library! Good work!)

**Comment by JimBobSquarePants** [comment]
No worries :smile: 

I have actually considered that suggestion but that would leave the aspect ratio wildly different to what is requested. In this example we'd get 363/12787 (fraction is already in its simplest form) instead of 1/16.
