### ISSUE TITLE
Azure Blob Cache - Feedback/Notes

### ISSUE THREAD

**Issue by uniquelau** [JimBobSquarePants/ImageProcessor#495]
Hi! Firstly massive thumbs up, this is great! I wanted to share some of my experiences, as we've got a website using this, that has LOTS of images, most of which are large assets (2000px+, high quality jpg).

Things I have noticed:
## 1. Occasional 404's when loading multiple images on the page

The more images we place on the page the higher the percentage of images that can't be served.

When StreamCachedImage is false, we see a combination of 404 & 500 errors.
### Error 2 (500)

```
 An unhandled exception occurred
 System.Net.WebException: The operation has timed out
    at System.Net.HttpWebRequest.GetResponse()
    at ImageProcessor.Web.Plugins.AzureBlobCache.AzureBlobCache.<>c__DisplayClass14_0.     <RewritePath>b__2()
    at ImageProcessor.Web.Plugins.AzureBlobCache.AzureBlobCache.TryFiveTimes(Action delegateAction, Action exceptionAction)
    at ImageProcessor.Web.Plugins.AzureBlobCache.AzureBlobCache.RewritePath(HttpContext context)
    at ImageProcessor.Web.HttpModules.ImageProcessingModule.
 <ProcessImageAsync>d__32.MoveNext()
```
### Error 1 (404)

```
 ImageProcessor.Common.Exceptions.ImageProcessingException: RewritePath 495 : Unable to rewrite      cached path to:      http://dmb.azureedge.net/cache/6/b/0/d/6/d/6b0d6dc97d8ce33c46ec4c39988d8a6be3a631bf.png
```

When StreamCachedImage is true, this issue disappears.

The site is running on a Medium Azure instance and my little Surface, so there should be enough grunt to deal with the requests! ;-)
## 2. How long are the assets cached for? Looking at request performance, it seems the Images are dropped out of cache within the hour.

Cheers! Laurie

**Comment by JasonElkin** [comment]
The best solution I've found (also using in production with large images) is to set StreamCachedImage to true and then place a CDN in front of ImageProcessor (rather than behind).

So the logic looks like this...

1. User requests image directly from CDN.
2. If image does not exist, CDN requests one from ImageProcessor.
3. CDN caches the image.

This largely ignores ImageProcessor's own cache when it comes to actually serving images but has a significant performance boost as we're not sending back lots of redirects (new HTTP connections that the client has to make).

**Comment by JimBobSquarePants** [comment]
Hi @uniquelau so sorry for not getting back to you on this sooner! I meant to do so after releasing the last update. I'll try to answer your questions.

1. I fixed the issue that you were seeing where images were not getting redirected. One of the CDN options on Azure (I forget which) can be pretty slow when first setting up images so timeouts occur which used to not be handled properly. I now correctly check and fallback to blob storage after 1000ms [configurable](http://imageprocessor.org/imageprocessor-web/plugins/azure-blob-cache/#config) so you are always served an image no matter what. [v1.1.3](https://www.nuget.org/packages/ImageProcessor.Web.Plugins.AzureBlobCache/1.1.3) onwards.
2. I set the headers to cache to the same defaults as the desk cache. 365 days on the server, 7 days in the browser. If you have any further detail you can share that would be great.

@JasonElkin Thanks for pitching in. 😄 That approach should work well. 

I'd love to see a diagram if you could to show exactly how you've set that up on Azure if you could for others to see? I've personally never had the opportunity to set it up like that myself so I'm also very curious.

This conversation seems like a good place to instigate a new one on how we could improve the cache. I originally wrote the initial solution in a couple of hours so it would be great to revisit the design.

So... 

1. What do you see as the main shortcoming of the current cache design?
2. How can we better design the caching and serving process?

Personally I would love to be able to remove the redirects. They only exist because the url is determined not only by the image request url but by the file size and last write time of the image itself. (This allows versioning which is important.) If we can figure out something smarter there's massive performance boosts to be had.

Looking forward to your input.

James

**Comment by JasonElkin** [comment]
Thanks @JimBobSquarePants, here's a few thoughts - diagram to follow.

1.  What do you see as the main shortcoming of the current cache design?

I have a suspicion that streaming cached images from the CDN is actually slower than accessing blob storage directly - I'm due to do some performance testing on a deployment this week so I'll have the chance to do some real-world testing and will feed back what I find.

Methods like `IsNewOrUpdatedAsync()` are fast and trivial tasks for a local filesystem, but blob storage is basically just a NAS and has network overheads. The only solution I can see to get around this is to implement some kind of index to keep track of the cached images without having to make extra requests.

All that having been said, the **_main_** issue, as I see it, is that blob storage is always a REST request away.  Any type of cache that's backed by blob storage will either create extraneous redirects, or it act as a proxy - neither of which are particularly efficient options. 

2. How can we better design the caching and serving process?

Where we're using ImageProcessor in-app (as opposed to as a standalone/remote server) we could use a method at render time to query the cache (perhaps still with the help of an index) and write the correct URL directly in-app/page.

That way we can leverage blob storage and/or a CDN for serving the cached files directly.

**Comment by JimBobSquarePants** [comment]
Hi @JasonElkin ,

Internally the Azure Blob Cache uses a memory cache to reduce some of the overheads but yeah, checking whether the item has been updated or is new is a hassle. An indexer would be an idea but as soon as you start scaling instances then that index could get out of sync. 

As for the second suggestion... I have been working on an approach that does the following.

1. On render call a method that gets the image URL.
2. In that method make a head request to the URL and cache the redirected response. Any redirects will give us the CDN url
3. Return the cached response URL and render that on the page.

That shouldn't slow down page render too much on first hit as long as appropriate timeouts and handling are set on the request.

**Comment by JimBobSquarePants** [comment]
I've done a **lot** of updates recently to the cache to improve performance. Please give the latest version a go and let me know what you thing.

**Comment by LemonTVnz** [comment]
Any progress or a branch with the url work?

**Comment by JimBobSquarePants** [comment]
Cached file names are now predictable. There's a static method in ImageProcessor.Web **CachedImageHelper.GetCachedImageFileName** that you can now call to get the cached file name as a hash. 

The rest you would have to do yourself since I don't produce framework specific consumer code. I do have the guts of a method in another library of mine that is doing what I described. It uses code specific to the CMS I'm integrating with though. https://github.com/JimBobSquarePants/Zoombraco/blob/bb5a1f2c7ce8566951249bda86e7a4d4afa80cc3/src/Zoombraco/Models/MediaTypes/ImageExtensions.cs#L91

I do, however need to release an update that handles an odd bug in Azure where requesting the CDN result via a head request can return a 500 code yet also the correct response object. The code is written, just not released.

**Comment by JimBobSquarePants** [comment]
There's been so many updates to both .Web and the Azure cache since this was opened I can't count them. Basically performance is waaaaaay better and I can handle Azure weirdness better so I'm gonna close this now.
