### ISSUE TITLE
PreserveExiffData makes gif look weird

### ISSUE THREAD

**Issue by mortenbock** [JimBobSquarePants/ImageProcessor#499]
Sorry for the image heavy issue, but that's all I have right now :)

When running this code:

![codesample](https://cloud.githubusercontent.com/assets/1760256/19589667/ed0a2f00-976d-11e6-9b3e-5dfe35f76298.jpg)

On this file:

![svinemoerbrad](https://cloud.githubusercontent.com/assets/1760256/19589668/ed0a39f0-976d-11e6-8e9c-8748590bb3df.gif)

The result is a bit weird:

![result](https://cloud.githubusercontent.com/assets/1760256/19589694/05dd57aa-976e-11e6-8700-790043838534.jpg)

If I turn off the PreserveExiffData it looks fine.

Using the following packages:

```
<package id="ImageProcessor" version="2.4.4.0" targetFramework="net461" />
<package id="ImageProcessor.Web" version="4.6.4.0" targetFramework="net461" />
```

**Comment by JimBobSquarePants** [comment]
Hey @mortenbock , Sorry I have't forgotten about this, just been focusing hard on [ImageSharp](https://github.com/JimBobSquarePants/ImageSharp).

System.Drawing stores some really odd things in the PropertyItems collection that really should be separated out so I'll have a look and see what is getting preserved or altered that shouldn't be. Gifs are a bit  of a nightmare to work with since the System.Drawing support is so poor.

**Comment by mortenbock** [comment]
No rush. I don't need the exiff data at the moment, but just thought it was a bit weird that it had this kind of impact :)

**Comment by JimBobSquarePants** [comment]
Fixed as part of https://github.com/JimBobSquarePants/ImageProcessor/commit/62306ea8833219620280b1a2b73e8e391a2df62d

Turns out I was reverting to the default System.Drawing encoder on save which couldn't seem to handle the  property items. With my augmented encoder I can't preserve the data anyway as I have to inject code into the byte stream in order to make animations/transparency work.
