### ISSUE TITLE
ImageProcessor.PostProcessor disable or cancel process option

### ISSUE THREAD

**Issue by TomSteer** [JimBobSquarePants/ImageProcessor#513]
Hey, 

Would it be possible in some way to disable PostProcessing on certain image types e.g. jpgs.
This could be done by firing an event which is cancelable or through some config file.

The reason I ask is we already do some preprocessing on jpgs (using mozjpeg) when uploaded to Umbraco so wouldn't want these files to be processed again in the PostProcessing process.

Cheers and high five for all your great work James :)

Tom

**Comment by JimBobSquarePants** [comment]
Hi Tom,

Thanks for your kind words 😄 

There aren't any options. This is for good reason. 

I'm afraid to say but you're wasting your time preprocessing images if they are going to then be resized or cropped using ImageProcessor without postprocessing. This is because the Jpeg encoder built into System.Drawing does not use any subsampling to more efficiently store pixel data. 

As soon as you save the image, any preprocessing is lost. The same goes for all the other built in encoders.

Hope that makes sense to you.

Cheers

James

**Comment by TomSteer** [comment]
Hey James,

Thanks for coming back so quickly 👍 We are using it to reduce the amount of disc space used when clients upload large image files. Based on what you've said above, could they be ran in parallel? Prepossessing to reduce the disc space usage of the original file and post processing to deal with the cached ImageProcessor images?

Cheers, 

Tom

**Comment by JimBobSquarePants** [comment]
Sorry Tom,

Totally thought I'd replied to this. Yeah, no harm at all. They'll get processed before caching and save a good deal of space.

If you are worried about disk space though I would recommend moving your media to blob storage. 

Cheers

James
