### ISSUE TITLE
Multiple levels of cache

### ISSUE THREAD

**Issue by alejandroMunozMulet** [JimBobSquarePants/ImageProcessor#516]
Hi Jim,

First of all, congrats, you did a really good job with image processor, totally loving it, I had my own imageservice working in les than an hour... definetly need to donate for atleast a beer for you.

One thing that I came across and I did not found in documentation is suporting various levels fo cache, its kind of confusing because in the cache config looks like you can set multiple caches but I don't see anyway how to do it...

My Idea is to create 3 levels of cache:
-Memory (own implementation) for really small images and frequently requested images
-Redis for another level of cache with a limited set of images that are big and higly requested (i'm not sure if im going to actually use it because I have to do proper load testing to see if there is really a performance gain.
-DiskCache / BlobCache (need to decide ) for  everything else.

I just need to know if there is any way to do what I actually have in mind, because acording to documentation I am not really sure how.

I guess that my best option is to extend the DiskCache / blobCache and create the multilevel inside it, but I wanted to keep it separated if posible.

Cheers.

**Comment by JimBobSquarePants** [comment]
Hi @alejandroMunozMulet 

Thanks for your message, It's always great to hear that my work is helpful 😄 

There's no documentation on that process because it's not supported. You never really want to hold an image, no matter how small, in memory - They simply take up too much space that could be required elsewhere. For image processing to be successful under load you need at least 1GB of contiguous memory available to GDI+ or else you'll start to get out of memory exceptions when processing even small files.

Internally the DiskCache holds a an in-memory store that contains a reference to the cached location. You can see that [here](https://github.com/JimBobSquarePants/ImageProcessor/blob/e986b06d010a4858b3a1442767d5ae8e329cc16f/src/ImageProcessor.Web/Caching/DiskCache.cs#L116). That indexer allows for fast location mapping to the file system without having to  make a request. You can't get much quicker than the indexer. After that it's best for us to let the IIS StaticFileHandler take over on redirect. both that and the operating systems file system are so finely tuned for rapid access there's simply no point in trying to beat it. By introducing a Redis cache you would be adding overhead. 

I also do the same for the [AzureBlobCache](https://github.com/JimBobSquarePants/ImageProcessor/blob/e986b06d010a4858b3a1442767d5ae8e329cc16f/src/ImageProcessor.Web.Plugins.AzureBlobCache/AzureBlobCache.cs#L189). Though admittedly, I hate the reliance I have on the 302 redirect I have there. 

The multiple caches identified in the configuration documentation are either/or.  A single cache would inherit [`ImageCacheBase`](https://github.com/JimBobSquarePants/ImageProcessor/blob/e986b06d010a4858b3a1442767d5ae8e329cc16f/src/ImageProcessor.Web/Caching/ImageCacheBase.cs) (or implement `IImageCache`) and you would choose which of those caches to implement that single cache does the grunt work.

Does that make sense?

Cheers

James

**Comment by alejandroMunozMulet** [comment]
Hi James, 

First of all thanks for your response is really nice to have such a complete explanation by someone who probably has better things to do. 

Yes it makes absolute sense,  I guess I have got way too obsesed with performance that I have literally overthink it,  and missjudged the need of memory that image processing takes. 

My main concern was the load that the service is going to take,  wich is going to be really huge,  and avoid any service degradation. 

But I think the smart thing to do is stay with the disk cache, and just scale horizontally if the load gets really really huge And not try to optimize which really doesnt need any optimization. 

Thanks for your time,  you really deserve that beer. 

cheers.

**Comment by JimBobSquarePants** [comment]
Thanks @alejandroMunozMulet 

If I have any advice from my experience to give to you it would be this.

Never think that someone who owns a code repository, no matter how popular it is, has better things to do than listen to your suggestions. 

We all have something to learn.

I know a little bit more than most about image processing. I've studied very hard and am reaping the benefits of my efforts. Does that make me infallible and unable to learn? Absolutely no! I am constantly seeking to gain better knowledge about a myriad of technologies my software can integrate with. I'm constantly eager to learn more about image processing too!

Our conversation, and many like it, serve as a catalyst for the evolution of not just this project, but for software development as a whole.  We progress by learning collaboratively. 

We better ourselves and serve our industry and the people that consume it together; collaboration is paramount to successful development. 

I hope that this conversation fuels a greater involvement for you in open source software and that you go on to lead in developing great solutions for others. 

Thank you for your efforts. 

P.S If you do ever spot something funky in my code, please open an issue.
