### ISSUE TITLE
Throws: Only 8bpp, 24bpp and 32bpp images are supported when requesting image 1bpp with querystring

### ISSUE THREAD

**Issue by rasmuseeg** [JimBobSquarePants/ImageProcessor#548]
Hi there,

Throws: Only 8bpp, 24bpp and 32bpp images are supported when requesting image 1bpp with not valid imageprocessor querystring.

The following url works:
http://dtukvv.dk/content/images/pagenav-submenubg.png

But adding a parameter like:
http://dtukvv.dk/content/images/pagenav-submenubg.png?1481717299

throws the following error:
![image](https://cloud.githubusercontent.com/assets/1511208/22146103/db049fba-df03-11e6-83df-fec994ecd4c0.png)

Should it not ignore this querystring?

**Comment by JimBobSquarePants** [comment]
Yes it should but that's also an invalid querystring. It should be a key\value pair. .

**Comment by rasmuseeg** [comment]
Perhaps, but its generated by compass when using image-url(path/to/file.png)

**Comment by JimBobSquarePants** [comment]
No worries, I'll recreate and have a dig around.

**Comment by JimBobSquarePants** [comment]
So it turns out you're using **ImageProcessor.Web 4.4.0** (If I can figure that out you probably should have been able to tell me 👅 )

 Versions after 4.6.0 will correctly throw an error with the message 

>The request {Url} could not be understood by the server due to malformed syntax.

This behavior is designed to help prevent denial of service attacks against your server and the change is documented [here](http://imageprocessor.org/imageprocessor-web/)

Validating the parameter is performed via the `ImageProcessingModule.ValidatingRequest` event documented [here](http://imageprocessor.org/imageprocessor-web/imageprocessingmodule/#events)

I would update your version to the latest one and add the validation.

Cheers

James

**Comment by rasmuseeg** [comment]
@JimBobSquarePants So sorry about the wild goose hunt. 

> The request {Url} could not be understood by the server due to malformed syntax.
So it's still preventing me from using 1bpp images if they have a querystring?

**Comment by JimBobSquarePants** [comment]
No, all images are converted to 32bpp images for processing.

**Comment by JimBobSquarePants** [comment]
Also... No worries, it happens. :smile:
