### ISSUE TITLE
PostProcessor - issues with large images?

### ISSUE THREAD

**Issue by Slowacki** [JimBobSquarePants/ImageProcessor#552]
I'm running Umbraco 7.4.3 in Azure with ImageProcessor 4.5.3. Recently, I've decided to install PostProcessor (v1.1.0) for some improved performance (who wouldn't want that right?). At first it worked great, I could notice the size of some images to shrink a lot and there didn't seem to be any issues. 

However, quite recently, I've seen some errors in the logs, which look like that:

> ERROR Umbraco.Core.UmbracoApplicationBase - An unhandled exception occurred
> System.IO.IOException: The process cannot access the file 'D:\local\Temp\tmp9523.jpg' because it is being used by another process.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.File.InternalDelete(String path, Boolean checkHost)
>    at ImageProcessor.Web.Plugins.PostProcessor.PostProcessor.PostProcessImage(MemoryStream stream, String extension)
>    at ImageProcessor.Web.Plugins.PostProcessor.ApplicationEvents.PostProcess(Object sender, PostProcessingEventArgs e)
>    at ImageProcessor.Web.HttpModules.ImageProcessingModule.<ProcessImageAsync>d__b.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar)
>    at System.Web.HttpApplication.AsyncEventExecutionStep.OnAsyncEventCompletion(IAsyncResult ar)

Did some digging and it seems this only happen with rather big images, however, size doesn't seem to be the only factor. The image it's always breaking on is 6.9MB. I've uploaded some other big images to check it out, it didn't break for other ones around 7MB, but it did break for anything close to 10MB. Those were all jpgs. Any idea on this and how to fix it?

**Comment by JimBobSquarePants** [comment]
Hi @Slowacki

I had a look at what was happening and it turns out the problem was the following.

When postprocessing image files I put a limit of 5 seconds on the optimizers to do their thing and return the stream. If the optimizer was taking too long (large jpegs) then the process running the embedded optimizer was not disposed of properly (as I was returning early) so it wasn't releasing the file. This fix should handle that. 

I've padded out the code with another coupld of safety nets also.

I'll get a new release out asap.

Cheers

James
