### ISSUE TITLE
[Question] image.Pixels.Length vs (image.Height * image.Width)

### ISSUE THREAD

**Issue by lggomez** [JimBobSquarePants/ImageProcessor#565]
Sorry if the question seems too basic beforehand 

I made a small app using ImageProcessor and I came upon this behavior, so I'd like to know the rationale behind this. The Pixel array length is usually way larger that the H*W value, thus making pixel traversals a bit awkward and having to resort to truncation according to the Height and Width

Example: Using mi profile picture (jpg) I get the following:
Expected (H*W): 78961
Actual (Pixels.Length):131072

Thanks in advance

**Comment by JimBobSquarePants** [comment]
Hi @lggomez 

Questions like this are best suited to [Gitter](https://gitter.im/JimBobSquarePants/ImageProcessor) not the issue tracker. You'll have read that in the [contribution guidelines](https://github.com/JimBobSquarePants/ImageProcessor/blob/develop/.github/CONTRIBUTING.md) before you deleted the issue template I'm sure though.

I'll attempt to answer here though since you've thrown me right off with your question.

What do you mean by Pixels? Nothing in ImageProcessor has that property.

**Comment by JimBobSquarePants** [comment]
@lggomez Could you kindly explain why you have closed this issue?
