### ISSUE TITLE
Add different options for preserveExifMetaData to preserve varying amount of data

### ISSUE THREAD

**Issue by Jeavon** [JimBobSquarePants/ImageProcessor#585]
### Description
There are scenarios where it is necessary to preserve different levels of Exif data, I would like to propose the following options are added to the preserveExifMetaData setting of processing.config

- all (also "true" for upgrade compatibility) - preserves all EXIF data
- copyrightOnly - preserves only the Copyright field
- minimal - preserves Copyright, DateTime , ExifUserComment, ImageDescription, and all fields relating to the camera, lens, exposure, etc
- minimalWithLocation - the same as minimal but including all GPS related fields

It could also be possible that a custom set of fields might be required, this would require a more complex configuration and may not be required frequently.

All fields can be viewed at https://github.com/JimBobSquarePants/ImageProcessor/blob/fef782988e5f39e536a1a303ed320dc061a68134/src/ImageProcessor/Imaging/MetaData/ExifPropertyTag.cs#L64

That's my opening sugesstion, hopefully others can provide a more conclusive list for each category

**Comment by drobar** [comment]
I like the idea. I've had various need for some exif data in various projects and had similar requests from ImageGen users. There is value in having access to copyright, author, and description and similar 'descriptive' details. And camera settings in some cases. And location/gps info in some cases.

A real problem with 'retain all exif data' is that non-destructive image editing software such as Lightroom embeds all instructions in the exif. Which can easily create 100KB to megabytes of exif data that is useless for the purposes of resizing and is of little or no value after resizing because the pixel locations will be irrelevant after resizing.  Editing information should always be removed unless specifically set to retain it (which would 99.9% of the time be foolish but I guess we can imagine a situation where it would be useful).

The total weight of typical non-editing-data isn't huge. Less than 3-10KB in my experience. Though if you're resizing to a thumbnail size even that could double the size of the image sent to the website visitor.

I'd recommend these options:
- None = remove all exif data
- Minimal = retain all non-editing data [Default setting]
- All = retain all exif data

It gets a bit tricky with ICC profiles but I guess if they are used and supported at resize time then they should be retained no matter what option is chosen. Though system.drawing ain't great with ICC so maybe this isn't a real concern. Worth mentioning in this context though, just in case.

As for a 'custom' option, that would be great because someone will need copyright but not author. They'll want description but not tags. Or to keep all but remove location info.  I could argue for allowing a series of categories to be listed, which would make it more obvious for users who aren't exif experts (and who is?!). To be overly tricky, use plus and minus to simplify adding or removing a few items without listing them all. For example: None+Copyright or Minimal-Location or just list the categories you want such as +Copyright+Description+Author. Categories might include:
- Copyright
- Description
- Author
- Tags
- Camera
- Location
- ??

Adobe Lightroom has a few settings that might be helpful to the discussion: https://helpx.adobe.com/lightroom/help/metadata-basics-actions.html

Okay, that's a brain dump before I forget it all ;)

**Comment by PeteDuncanson** [comment]
This one came up again as part of this twitter convo:

https://twitter.com/thechiefunicorn/status/970294155351126022

And related to adding the post processor to Umbraco as standard:

http://issues.umbraco.org/issue/U4-11051

Would certainly be nice to add. Personally I'd go with copyright and then as few others as we can get away with.

**Comment by Matthew-Wise** [comment]
@JimBobSquarePants You got any pointers on where I should be looking to have a go at adding this feature?

Cheers
Matt

**Comment by JimBobSquarePants** [comment]
If someone can list me out the required copyright EXIF fields then I'll rattle through this. 

It's probably best if I do it as it'll only take about an hour of my time and there's stuff stored in `System.Drawing`'s `PropertyItem` collection that we do not want to accidentally remove.

I'm gonna go with the following suggestion from @drobar  with a slight tweak.

- `ExifRetentionMode.None` = remove all EXIF data
- `ExifRetentionMode.Minimal` = retain all data pertaining to ownership. Copyright etc.
- `ExifRetentionMode.All` = retain all EXIF data

I can't set Minimal to default code-wise as that would be a breaking change though there's nothing to stop Umbraco making it the default in their config.
