### ISSUE TITLE
Bug in Resize.Pad without upscale

### ISSUE THREAD

**Issue by capjan** [JimBobSquarePants/ImageProcessor#588]
Resizing an image with dimensions 400x1000 to 450x400 results in an image with the original dimensions. If I allow upscale then the result is as expected.

**Comment by JimBobSquarePants** [comment]
Please don't delete the issue template.

That is expected behaviour. Since you are upscaling the width which would not be allowed.

**Comment by capjan** [comment]
Hello Jim,
thanks for the fast reply.

Just for clarification, why is this expected behavior?

`
using (var factory = new ImageProcessor.ImageFactory())
{
  // input image (400x1000)
   factory.Load(inputImage)        
   .Resize(new ResizeLayer(new Size(450, 400), ResizeMode.Pad, upscale: false))                
   .Save(outputImage);
}
`
I expect a centered image of 160x400 (to keep the aspect ratio) on a black background.

**Comment by JimBobSquarePants** [comment]
No worries, The limit is on both dimensions. While you are scaring down one dimension you are still scaling up the other one. As such you get the original image back.

**Comment by Obscuras** [comment]
Hi Jim,

I like to add my 50 cents too. In my opinion the definition of "upscaling" is the problem here.
According to capjans description the resulting image is much smaller, only the padding afterwards makes it wider then the original.
But the original image is downscaled, much smaller than before. This is what I would expect too when I turn upscaling off.

I recommend to compare the requested size with the resized image size (before the padding) to see whether it is upscaled or not and apply the padding afterwards.

**Comment by JimBobSquarePants** [comment]
Hi @Obscuras You're entitled to your opinion of course but I'm not going to change the behavior. It's been like this for years without complaint.
