### ISSUE TITLE
How to change default bgcolor from black to transparent ?

### ISSUE THREAD

**Issue by eupzry** [JimBobSquarePants/ImageProcessor#594]
### Description
Is there any wat to change default background color from black to transparent? And of course , If image format does not support transparent background, the background should be white. I am trying to swapping imageprocessor library from x to yours. I have alot of client application. Adding bgcolor qs to all imageurl that will be terrible. If there any possibility for this, it will be very good for me.

### Steps to Reproduce
When i send with and height via querystring, if the requested ratio different than original ratio, the response will be come with black pad bars.

- ImageProcessor version: **2.5.4.0**
- ImageProcessor.Web version: **4.8.4.0**
- .NET Framework version: **4.6.1**

Thanks in advance

**Comment by dampee** [comment]
Hi,

I think black is fine. :-)

You can change the defaults by changing the presets as described in the [configuration documentation](http://imageprocessor.org/imageprocessor-web/configuration/#processingconfig).

Kind regards
Damiaan

**Comment by JimBobSquarePants** [comment]
@eupzry blasck is actually the correct output since it represents an empty pixel. 

You should use the events described in the [documentation](http://imageprocessor.org/imageprocessor-web/imageprocessingmodule/#events) to either change the resize mode to crop (recommended) or change the bgcolor to white. 

Any further questions please let me know.

Cheers

James

**Comment by JimBobSquarePants** [comment]
@eupzry blasck is actually the correct output since it represents an empty pixel. 

You should use the events described in the [documentation](http://imageprocessor.org/imageprocessor-web/imageprocessingmodule/#events) to either change the resize mode to crop (recommended) or change the bgcolor to white. 

Any further questions please let me know.

Cheers

James

**Comment by eupzry** [comment]
Thank you @JimBobSquarePants & @dampee
