### ISSUE TITLE
Ability to subclass image services

### ISSUE THREAD

**Issue by softwords** [JimBobSquarePants/ImageProcessor#602]
In many cases, it would be simple to implement IImageService by sub-classing an existing services (such as CloudImageService) and overriding the particular methods (such as IsValidRequest).

Unfortunately, in CloudImageService , the methods implementing IImageSerivce interface are not virtual, so they cannot be overridden.

A simple change to make these properties and methods virtual would make it easier to build new image services.

**Comment by JimBobSquarePants** [comment]
Hi @softwords 

A good idea but serious question here before we continue. 

Why did you add the suggestion to the issue tracker (after deleting the template) rather than use the [Gitter channel](https://gitter.im/JimBobSquarePants/ImageProcessor?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) specified in the highlighted [contribution guidelines](https://github.com/JimBobSquarePants/ImageProcessor/blob/b45727d1371f01223f63bcfdd6b18d68535c1911/.github/CONTRIBUTING.md#do-you-intend-to-add-a-new-feature-or-change-an-existing-one)?

**Comment by JimBobSquarePants** [comment]
I'll release an update today which allows overriding the two main methods in each service `IsValidRequest` and `GetImage`
