### ISSUE TITLE
Image Resize Quality

### ISSUE THREAD

**Issue by GaryLProthero** [JimBobSquarePants/ImageProcessor#603]
I am uploading three images

**The Original:** Original-cotton-chart gallery-figure 1.png
**The  resized version using the ImageProcessor Library:** cotton-chart gallery-figure 1_600px.png
**The resized version using Photoshop:** photoshop-cotton-chart-gallery-figure-600.png

When the image is resized using the ImageProcessor library the text is much lighter than when the same image is resized using Photoshop.

Here's the code I am using:

                using (ImageFactory imageFactory = new ImageFactory(preserveExifData: true))
                {
                    Size resizeValue = new Size
                    {
                        Width = maxWidth,
                        Height = maxHeight
                    };

                    ResizeLayer resizeLayer = new ResizeLayer(resizeValue, ResizeMode.Max);

                    if (System.IO.File.Exists(newFilePath))
                    {
                        System.IO.File.Delete(newFilePath);
                    }

                    try
                    {
                        // Load, resize, set the format and quality and save an image.
                        imageFactory.Load(image)
                            .Resize(resizeLayer)
                            .BackgroundColor(Color.White)
                            .Quality(100)
                            .Save(newFilePath);
                    }
                    catch (SystemException ex)
                    {
                        string msg = ex.Message;
                    }
                }

How can I improve the image to Photoshop quality?

Thanks

Gary Prothero
gary@proworks.com

![ip-cotton-chart gallery-figure 1_600px](https://user-images.githubusercontent.com/2007440/27049548-86b77e74-4f64-11e7-9d60-b049e7fbc2f8.png)
![original-cotton-chart gallery-figure 1](https://user-images.githubusercontent.com/2007440/27049547-86b2b54c-4f64-11e7-9d27-882421db6044.png)
![photoshop-cotton-chart-gallery-figure-600](https://user-images.githubusercontent.com/2007440/27049546-86b1e48c-4f64-11e7-8e52-7df5f91e74ff.png)

**Comment by JimBobSquarePants** [comment]
Hi @GaryLProthero 

Does this issue happen when simply decoding/encoding the image or just during resizing?

ImageProcessor is simply a wrapper around System.Drawing and will suffer the same caveats when processing images. As such, my hands are tied for thing such as this.

If the problem happens when simply  decoding/encoding the image it will be due to poor management of the sRGB and Gamma chunks within a png which I cannot control. 

If it happens during resizing then this is due to whatever resampling algorithm System.Drawing uses to resize the image. Again, not something I have any control over. My guess is that it is the algorithmic differences.

I had a quick look at the output images using a png analyser and I noticed both images contain textual chunks that are not in the original image? How are these getting added?

Cheers

James

**Comment by GaryLProthero** [comment]
James, 

Thanks for the response. I noticed that the original image was 24 bit, the photoshop image after resizing was 24 bit. However, the image resized with ImageProcessor was 32 bit. Is there a way to maintain (or set) the image to 24 bit? 

Gary

**Comment by JimBobSquarePants** [comment]
Hi Gary,

No I'm afraid not. We convert to 32bit internally for perf reasons and to provide consistency across all formats (plus there's some internal code that requires 32bit)

I've no way of knowing what someone has done to an image once I have loaded it so we have to have a default that allows all scenarios. 

Cheers

James
