### ISSUE TITLE
Using Gaussian Blur makes CPU Usage spikes at 100%

### ISSUE THREAD

**Issue by bevss** [JimBobSquarePants/ImageProcessor#607]
### Description
Hi James, I just have a question with regards to your library ImageProcessor. I use the Gaussian Blur to blur the images on the fly but my CPU Usage spiked at 100%.

Is this a hardware problem? and is ImageProcessor using CPU to blur images? If yes, upgrading CPU with more cores and speed will work? If not, can ImageProcessor make GPU handle the blur process? Lastly if GPU can handle the blur process, having GPU will help to lower the CPU Usage?

### System Configuration
- ImageProcessor version: Latest
- Environment (Operating system, version and so on): Windows 7
- .NET Framework version: 4.6

Thanks

**Comment by JimBobSquarePants** [comment]
Hi @bevss 

Since I don't know any details about your use case (blur width, etc) I can't really comment specifically.

The Gaussian blur algorithm in ImageProcessor is a naive implementation based on AForge. Basically this means that instead of using a fast 2-Pass linear algorithm it's uses a 2D one pass algorithm which gets more intensive (slowing down, more CPU) the wider the Gaussian kernel you apply.

It doesn't use GPU. But yeah, boosting the CPU Count will help. 

Unfortunately there is little I can do about this without changing the signature (Which means a major version)  and I don't plan on doing this any time soon as I'm focusing on [ImageSharp](https://sixlabors.com/projects/imagesharp/) Which incedentally uses the much faster 2-Pass algorithm.

Hope that is all clear.

Cheers

James

P.S (Latest means nothing to anyone reading this, version numbers are paramount)
