### ISSUE TITLE
Cache trimming seems to still be very cpu consuming

### ISSUE THREAD

**Issue by ZNS** [JimBobSquarePants/ImageProcessor#612]
### Description
Cache trimming is very cpu intensive. We have a server which runs pretty much only two small imageprocessor web applications. The server has been under pretty heavy CPU load averaging about 50% at all times. Finally tried to disable the cache trimming and immediately the CPU usage dropped to avg. 3%.

![CPU Stats](https://image.prntscr.com/image/ENQyq6YzQBiMyVhUqI38rA.png)

### Steps to Reproduce
Disable cache trimming by setting trimCache="false" in the cache config file. CPU load drops.

### System Configuration
- ImageProcessor version: 2.5.4
- ImageProcessor.Web version: 4.8.4
- Environment (Operating system, version and so on): Windows server 2016 M4 instance on AWS

**Comment by JimBobSquarePants** [comment]
Hi @ZNS 

It's simply due to the disk access. We've limited cache trimming runs, reduces allocations as much as possible but accessing the disk an looping through directories will always increase CPU.

I'm assuming you have a lot of changes in your site? The cache trimming mechanism only kicks in when a new image is cached.
