### ISSUE TITLE
Animated Gif manipulation massivly increases file size

### ISSUE THREAD

**Issue by CallyyllaC** [JimBobSquarePants/ImageProcessor#620]
Probably not a bug, but more of a question if I'm missing something important. Whenever I work with (rezise, add overlay ect) animated gifs, it un-optimises them to work with them, but then it doesn't re-optimise them after causing files sizes to increase dramatically. I know reducing the quality helps a little but is there a way of re-adding the transparency between the gif frames?
![2017-08-02_13-02-44](https://user-images.githubusercontent.com/16276325/28872873-f2d6f206-7782-11e7-8e34-7e6ff052cc2c.png)
here is the code I am using currently:

>             byte[] imgArr = File.ReadAllBytes(input);
>             using (MemoryStream inStream = new MemoryStream(imgArr))
>             {
>                 using (ImageFactory imageFactory = new ImageFactory(preserveExifData: true))
>                 {
>                     Size size = new Size(size1, size2);
>                     ISupportedImageFormat gifformat = new GifFormat { IsIndexed = false, Quality = 90 };
>                     ResizeLayer resizenew = new ResizeLayer(size, ResizeMode.Stretch);
>                     imageFactory.Load(inStream)
>                                 .Resize(resizenew)
>                                 .Format(gifformat)
>                                 .Save(output);
>                 }
>             }

**Comment by JimBobSquarePants** [comment]
Hi @CallyyllaC 

Yeah, not much I can do with them to be honest. I've had to hack the `System.Drawing` gif encoder in order to support animated gifs which means the palette is required for each frame. This'll definitely increase file size on most images, sometimes dramatically. 

You might also be increasing the size though during quantization if your original gif has less than 256 colors. The Quantizer, by default uses 256 but you can reduce this. 

I built a PostProcessor for ImageProcessor.Web that optimizes processed images for gif plus the others. Maybe you could adapt it to suit your needs on desktop? You can find it in this repo.

Hope that makes sense and helps.

Cheers

James

**Comment by CallyyllaC** [comment]
Okay, thanks for the help, I'll look into it.

**Comment by JimBobSquarePants** [comment]
Great. Let me know how you get on.
