### ISSUE TITLE
PostProcessor compression does not work for PNG images in Azure

### ISSUE THREAD

**Issue by Romanets** [JimBobSquarePants/ImageProcessor#626]
### Description
Everything works well on my dev PC, but after publishing to Azure App Service it is turned out that PNG files are not compressed after resizing,

### System Configuration
- ImageProcessor version: 2.5.5
- ImageProcessor.Web version: 4.8.6
- ImageProcessor.Web.Config version: 2.3.0.0
- ImageProcessor.Web.PostProcessor version: 1.2.3
- .NET Framework version: 4.6

**Comment by JimBobSquarePants** [comment]
Hi @Romanets 

Any logs?

**Comment by Romanets** [comment]
Hi @JimBobSquarePants, it dosen't write anything to log. For jpeg images compression works well locally PC and in Azure - the same size of file, but PNGs well compressed locally and much bigger in Azure. Also Google PageSpeed Insights tells me that PNGs are not optimized.

**Comment by JimBobSquarePants** [comment]
No worries,

Google PageSpeed actually checks for lossy compression, not lossless. So will be giving you the wrong report. Lossy compression can lead to an unacceptable loss in quality that the tool does not take into consideration.

I would compare both file sizes and also share the before and after images here. I'm able to compress png's on Azure as are others so I'm keen to see what is happening.

Cheers

**Comment by Romanets** [comment]
Hi @JimBobSquarePants, please see attached examples
[Image-optimisation-examples.zip](https://github.com/JimBobSquarePants/ImageProcessor/files/1309889/Image-optimisation-examples.zip)
 attached

**Comment by JimBobSquarePants** [comment]
Thanks I'll check these out asap

**Comment by ronaldbarendse** [comment]
@JimBobSquarePants The PostProcessor plugin already uses lossy compression for JPEGs larger than 10kb ([using cjpeg](https://github.com/JimBobSquarePants/ImageProcessor/blob/29ab88c2bbbcfdb2757a7f84c34637883626eea1/src/ImageProcessor.Web.Plugins.PostProcessor/PostProcessor.cs#L210)) and for PNGs ([using pngquant](https://github.com/JimBobSquarePants/ImageProcessor/blob/29ab88c2bbbcfdb2757a7f84c34637883626eea1/src/ImageProcessor.Web.Plugins.PostProcessor/Resources/Unmanaged/x86/png.cmd#L1)).

Since PNGs are processed multiple times (using pngquant and truepng), this could take more time than the timeout of [5000ms](https://github.com/JimBobSquarePants/ImageProcessor/blob/29ab88c2bbbcfdb2757a7f84c34637883626eea1/src/ImageProcessor.Web.Plugins.PostProcessor/PostProcessorBootstrapper.cs#L68) (which cannot be changed by the way!). Besides lower CPU/memory of Azure (vs. local), files are stored on a network share and also have to be copied within this time.

Logs are written as INFO. Maybe you don't see them, because the minimal log level is set higher (production environments are advised to set this to WARN)?

**Comment by JimBobSquarePants** [comment]
@ronaldbarendse I know what the postprocessor does. I wrote it.  

We're talking about png's here so the jpeg information is irrelevant. The lossy compression also uses the psychovisual testing via pngquant to determine whether the quality loss is acceptable. 

5000ms is more than enough time on an appropriately setup Azure instance. If it's not, i.e the setup it underpowered, then you shouldn't be using it for image processing anyway. 

And yes, you [can set that value](https://github.com/JimBobSquarePants/ImageProcessor/blob/36dcddd36ff259d1d100db0675a9a1cd90b2e153/src/ImageProcessor.Web.Plugins.PostProcessor/PostProcessorApplicationEvents.cs#L39). No need for the exclamation point there, drop the attitude. 

>Logs are written as INFO

Are they? I'm shortcircuiting `Debug.Writeline` in the [default logger](https://github.com/JimBobSquarePants/ImageProcessor/blob/29ab88c2bbbcfdb2757a7f84c34637883626eea1/src/ImageProcessor/Common/Exceptions/Logging/DefaultLogger.cs#L22) via reflection to run in release mode. There's an interface and configuration hooks to set your own logger so you can log however you like, hence my question.

**Comment by Romanets** [comment]
@JimBobSquarePants, @ronaldbarendse   I tried to set logger with `ImageProcessorBootstrapper.Instance.SetLogger()` method, but didn't get any messages logged. Also I tried to 'PostProcessorApplicationEvents.SetPostProcessingTimeout()' to 20 seconds, but haven't got any positive results.

**Comment by JimBobSquarePants** [comment]
Are you creating a new request? The originals will be cached mind.

**Comment by Romanets** [comment]
I removed all cached images with App Service Editor before testing

**Comment by ronaldbarendse** [comment]
@JimBobSquarePants Just trying to help here!

I didn't see the `SetPostProcessingTimeout()` method, only `PostProcessorBootstrapper.Timout`, my bad! Having a property with an internal setter in an internal class may have confused me here (could just be a public setter, since the scope is already restricted by the class).

The default 5000ms should indeed be enough, but my experience with PNG postprocessing is that large images may take quite some time to process. Together with possible limited resources in Azure and the overhead of the network share, the original image could be returned because of this. In that case it should add a [log entry](https://github.com/JimBobSquarePants/ImageProcessor/blob/29ab88c2bbbcfdb2757a7f84c34637883626eea1/src/ImageProcessor.Web.Plugins.PostProcessor/PostProcessor.cs#L151), but that could be filtered in a production environment, so I thought it was worth mentioning...

Any reason why the `DefaultLogger` doesn't use the default [`Trace.WriteWarning()`](https://msdn.microsoft.com/en-us/library/4f15e7w4(v=vs.110).aspx) that is by default also enabled in release mode?

You've written a nice, powerful library BTW! No downplay on that, great work! 👍

**Comment by JimBobSquarePants** [comment]
@ronaldbarendse No worries, Communication can be tough online sometimes. 😄 

To be honest, I can't remember. I added the logging so quickly I probably just grabbed the first thing I could think of.

@Romanets I'm at a loss. Would you be able to share your logger implementation code to see what is going on there? All this should just work and seems to.

**Comment by Romanets** [comment]
@JimBobSquarePants  I used image processor in Episerver solution, implementation is:
```
public class ImageOptimizationLogger : ILogger
    {
        private static readonly EPiServer.Logging.ILogger EPiLog = LogManager.GetLogger();

        public void Log<T>(string text, [CallerMemberName] string callerName = null, [CallerLineNumber] int lineNumber = 0)
        {
            string message = $"{DateTime.UtcNow:s} - {typeof(T).Name}: {callerName} {lineNumber}:{text}";
            EPiLog.Log(Level.Error, message);
        }

        public void Log(Type type, string text, [CallerMemberName] string callerName = null, [CallerLineNumber] int lineNumber = 0)
        {
            string message = $"{DateTime.UtcNow:s} - {type.Name}: {callerName} {lineNumber}:{text}";
            EPiLog.Log(Level.Error, message);
        }
    }
```

**Comment by Romanets** [comment]
@JimBobSquarePants Do you use Web App or Virtual Machine on Azure for testing?

**Comment by JimBobSquarePants** [comment]
@Romanets

That logger looks fine to me. I was hoping something would be off. 

 I use a local Web App plus a an Azure Web App for testing. I also dogfood, using the library in many sites.
