### ISSUE TITLE
Scharr Operator

### ISSUE THREAD

**Issue by peymangh** [JimBobSquarePants/ImageProcessor#634]
Hi,
I think there is a mistake in your Scharr Edge Detector. The horizontal kernel of this operator is (from your Wikipedia reference):
[+3 ,   0 ,   -3
 +10 , 0 ,  -10
 +3 ,   0 ,  -3 ]

but the kernel you wrote on `ScharrEdgeFilter.cs` is:

{ -3, 0, 3 }, 
{ -10, 0, 10 }, 
{ -3, 0, 3 }

So the result of your edge detector is different from the popular image processing libraries like OpenCV.
I think also the sobel operator has this problem.

Regards,
Peyman

**Comment by JimBobSquarePants** [comment]
Hi @peymangh 

Normally we'd use the Gitter channel for something like this unless you fill in the full issue template.

Mathematically it doesn't make a difference since the 2 pass algorithm performs the same operations. 

The OpenCV docs use the same kernel I do.

https://docs.opencv.org/3.3.0/d2/d2c/tutorial_sobel_derivatives.html

Are you absolutely sure you are applying a 3x3 filter when using OpenCV? Are you using the same grayscale transform? Do they do pre blurring to reduce noise?

Cheers

James
