### ISSUE TITLE
Set max file size in kb

### ISSUE THREAD

**Issue by Mackao** [JimBobSquarePants/ImageProcessor#637]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageProcessor
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageProcessor/issuess) and [closed](https://github.com/JimBobSquarePants/ImageProcessor/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Hi guys,
We use ImageProcessor on a lot of project, and we love it
We have some problems with uploading extremely big images that we need to scale down, so we can show them on our site
If I only set the ResizeLayer size, the uploaded images are too big in kb to be used on our site
My solution for this is to save the image with 100% in quality, if the uploaded image is to big, change the quality to 95 and resave the image, and repeat...
This takes a lot of time and processor power, but I don't know any other way to get the "right" file size

Should it be possible for you to add a "Max file size in kb"?
Or can you show me how to calculate this so that I only need to upload the file one time?

Best regards
//Marcus

### System Configuration
- ImageProcessor version: 2.5.4
- ImageProcessor.Web version (if applicable) 4.8.7
- Other ImageProcessor packages and versions:
- Environment (Operating system, version and so on): Windows 10, Visual Studio 2017
- .NET Framework version: 4.5.2
- Additional information:

**Comment by JimBobSquarePants** [comment]
Hi @Mackao 

>Should it be possible for you to add a "Max file size in kb"?

No I'm afraid not. There's no way to predict the output size other than to save the image. Especially with jpegs. There's simply too many variables and I don't know the exact inner workings of the System.Drawing encoder to even remotely guess.  

I'm intrigued by the kb requirements. 

Normally when scaling an image for a website you would set a maximum height/with to fit specific containers since images are for display purposes. That would give you a general range of filesizes but usually ones within acceptable limits. 

The only thing you need to concern yourself with then is using the correct file format e.g not png unless you require transparency.

Hope that makes sense.

Cheers

James

P.S Normally 75 is fine for the web. Anything above 90 really won't make a difference.
