### ISSUE TITLE
Configuration and performance of DiskCache vs AzureBlobCache? 

### ISSUE THREAD

**Issue by JimBobSquarePants** [JimBobSquarePants/ImageProcessor#638]
Migrated from the issue raised by @MichaelNielsenDK at https://github.com/JimBobSquarePants/UmbracoFileSystemProviders.Azure/issues/97

I've moved the media archive of a solution to blob storage, and figured it might be beneficial for image requests to not hit the webserver, as it's a high traffic solution.

So I've tested moving the image cache to blob storage with the AzureBlobCache package.

It works fine, but I noticed image requests are still hitting the webserver, but gives 302 redirects.

It seems to be slower than just using DiskCache, but I'm not entirely sure.

I can set StreamCachedImage=true, but that seemed to be even slower, and is also cautioned in the config comment here
http://imageprocessor.org/imageprocessor-web/plugins/azure-blob-cache/#config
when not using a CDN.

I wasn't planning on using a CDN, but traffic does come from multiple countries, so it could probably make sense.

So my question is, what configuration would be best for performance?

Keep using DiskCache, because that is just the fastest way to serve images?

Use AzureBlobCache without CDN and StreamCachedImage=false, because I shouldn't worry about the 302 redirects, and it's just as fast as DiskCache.

Use CDN+StreamCachedImage=true, because the benefits of the CDN and image requests not hitting the server is best.

**Comment by JimBobSquarePants** [comment]
@MichaelNielsenDK 

>Use CDN+StreamCachedImage=true, because the benefits of the CDN and image requests not hitting the server is best.

That's the one. The fastest, most scalable approach would be to configure a CDN directly to point to a simple web as described here https://github.com/JimBobSquarePants/ImageProcessor/issues/495#issuecomment-261299519

Failing that I would configure the DiskCache to run externally to the application so that each instance maintains an individual cache but it does so without the overheads of filesystem  watchers. 

Hope that helps

Cheers

James

**Comment by MichaelNielsenDK** [comment]
Hi @JimBobSquarePants , thanks for your patience and for migrating the issue, I wasn't sure where to ask it. 

I have just set to use DiskCache for now so I could move on with the project, but the comment you referenced seems the way to go, and I'll look into that later on. 

Thanks for the help.

**Comment by JimBobSquarePants** [comment]
No worries at all; happy to help 😄

**Comment by JimBobSquarePants** [comment]
@JarFrank I'd have a look ta this package.

https://github.com/CrumpledDog/Umbraco-AzureCDNToolkit

**Comment by c9mbundy** [comment]
@JimBobSquarePants I use that package on my V7 projects and it's nice, but I don't believe that is currently compatible with V8 ?

**Comment by JarFrank** [comment]
I have tried installing this package on V8 but as @c9mbundy said it is not compatible

**Comment by JimBobSquarePants** [comment]
I don't know then. Umbraco uses ImageProcessor.Web, not the other way round.

If you don't want to have redirect to a CDN using Umbraco you should either:

1. Port that project to V8 (Since you've been using it, it would be nice to give back)
2. Set up a slave Umbraco instance that is set as the end point for the CDN (with pass through enabled)and query the CDN url directly from all other instances.

**Comment by ronaldbarendse** [comment]
Using a CDN with Umbraco media has become trivial since version 8.1.0, as you only have to provide your own `IMediaUrlProvider`: https://github.com/umbraco/Umbraco-CMS/pull/5282.

If the media URL is prefixed with the CDN endpoint, no redirects are required and browsers connect directly to your CDN domain. The CDN is configured to point back to your website (e.g. `cdn.example,com` to `www.example.com/media`, with query string caching enabled), so ImageProcessor can process the images on the webserver and the response is cached by the CDN.

----------------

If you don't want to store the media files on the webserver, you can use [`UmbracoFileSystemProviders.Azure.Media`](https://github.com/umbraco-community/UmbracoFileSystemProviders.Azure) to put them in Azure Blob Storage. Because ImageProcessor needs to know how to load the original images (as they're not stored locally anymore), you need to configure `CloudImageService` (or `AzureImageService`) with the right prefix (as per documentation).

With this in place, it makes sense to also move the ImageProcessor cache into Azure Blob Storage using [`ImageProcessor.Web.Plugins.AzureBlobCache`](https://imageprocessor.org/imageprocessor-web/plugins/azure-blob-cache/). Because cached images are invalidated when the original image is updated and these aren't stored locally anymore, you can optionally configure the `SourceStorageAccount`/`SourceBlobContainer` (otherwise a basic `HEAD` HTTP request is done). If the CDN doesn't like the redirects, you can optionally set `StreamCachedImage` to `true`, although that will cause the webserver to proxy the cached image.

Both these packages require some configuration (which is the part that trips up most people), while it's not even required for setting up a CDN in front of your media/images.
