### ISSUE TITLE
PostProcessor and access-issues

### ISSUE THREAD

**Issue by enkelmedia** [JimBobSquarePants/ImageProcessor#662]
I'm using PostProcessor 1.3 on my Windows 2012 machine, and sometimes during startup I get this error in the log.

> RegisterExecutables 116 : Access to the path 'TruePNG.exe' is denied.,    at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
>   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
>   at ImageProcessor.Web.Plugins.PostProcessor.PostProcessorBootstrapper.RegisterExecutables(). Inner: 

Followed by this
Unable to install postprocessor - No images will be post-processed. Unable to map working path for processors.

I'm not sure if its related to permissions since it works sometimes, and sometimes not. Reg. permissions - is there any guidance around if and how one might need to setup any custom permissions for PostProcessor to work?

UPDATE: 
I also get this exception every now and then
`RunProcess 151 : Unable to post process image for request https://www.domain.com/_files/objects/12792/my-png-image.png?width=300&height=225&mode=crop within 5000ms. Original image returned.`

And as far as I can tell it's only when a PNG-image i processed, I'm wondering if the timeout of 5 sec is enough if the PNG is a big foto for example? Or maybe the issue is related to the permissions stuff above.

I also get this error randomly
```
System.UnauthorizedAccessException: Access to the path 'C:\Windows\TEMP\tmp46F-out.png' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at ImageProcessor.Web.Plugins.PostProcessor.PostProcessor.PostProcessImage(HttpContext context, MemoryStream stream, String extension)
   at ImageProcessor.Web.Plugins.PostProcessor.PostProcessorApplicationEvents.PostProcess(Object sender, PostProcessingEventArgs e)
   at ImageProcessor.Web.HttpModules.ImageProcessingModule.<ProcessImageAsync>d__34.MoveNext()
```

// m

**Comment by JimBobSquarePants** [comment]
That error is thrown here.

https://github.com/JimBobSquarePants/ImageProcessor/blob/102c265a6a0af3db744c4544b9feb524f8ef3e4a/src/ImageProcessor.Web.Plugins.PostProcessor/PostProcessorBootstrapper.cs#L116

This means that a running process is still holding onto the executable. 

I make an attempt to kill it though

https://github.com/JimBobSquarePants/ImageProcessor/blob/102c265a6a0af3db744c4544b9feb524f8ef3e4a/src/ImageProcessor.Web.Plugins.PostProcessor/PostProcessor.cs#L150

So I'm not sure what is going on. Disposing of the process should also kill it.

**Comment by enkelmedia** [comment]
@JimBobSquarePants Would it be possible that the process can'f finish the processing in 5 sec and then still "hangs on" blocking other attempts?

**Comment by enkelmedia** [comment]
I just tested with the command-line, the PNG that I tested on was about 1,7 mb - the command line process tok around 12-15 secs

Screenshot here:
https://www.dropbox.com/s/pq4kk0hq4pgkf1z/truepng.PNG?dl=0

Is is possible to configure the timeout? Or maybe have different timeouts for different formats? Or is it something wrong with my machine?

**Comment by ronaldbarendse** [comment]
This is related to issue #661. Also keep in mind that PNGs are optimized with `pngquant` and then also with `truepng` for maximum compression. So it probably takes more than 12 - 15 seconds for the post processor.

The default timeout of 5 seconds is more geared towards the end-user, because waiting longer probably defeats the additional download time of the unoptimized file. I think however that the file should then still be processed in the background for the next visitors, but that's probably not so easy (it should still need some timeout and update the existing cached file).

**Comment by JimBobSquarePants** [comment]
Thanks @ronaldbarends, definitely related.

I think further background processing though simply might not be possible with the current architecture. Ensuring we kill those processes for now should be our target.

**Comment by ronaldbarendse** [comment]
This problem is also found on the AzureJobs ImageOptimizer (https://github.com/ligershark/AzureJobs/issues/23) on which the code is based on, but that issue is open since 2014 and still not fixed...

I'll look into creating a PR with a full rewrite, so no child processes are started (currently you're starting `cmd` as parent process and for PNGs it's starting even more in the batch file)... I've got some ideas to wrap the processes in `Task`s, so continuations can be used or even parallel execution (although that would need some additional temp files with cleanup).

**Comment by JimBobSquarePants** [comment]
The problem there is that I need to pass the stream back to the HttpModule in order to save it via the cache. The PostProcessor has no knowledge of the cache nor should it.

**Comment by JimBobSquarePants** [comment]
Fixed in https://www.nuget.org/packages/ImageProcessor.Web/4.9.3.25

**Comment by enkelmedia** [comment]
High five man!
