### ISSUE TITLE
Image Rotation Improvement 

### ISSUE THREAD

**Issue by serkanozkul** [JimBobSquarePants/ImageProcessor#687]
In the current implementation,
Image rotate function changes the image size while rotating the image. The ask is adding parameter to select automatically crop while rotating so that rotating will keep the original image dimensions.

It is possible for users to crop but this takes lots of calculations for every user to do

**Comment by JimBobSquarePants** [comment]
Hi @serkanozkul 

I don't plan on adding any new features to the library since I am now concentrating on ImageSharp (See the [readme](https://github.com/JimBobSquarePants/ImageProcessor#contributing-to-imageprocessor)). 

The library itself is pluggable though so why not implement your own `CroppedRotateProcessor`?
