### ISSUE TITLE
Cached images with query not changing after image replacement

### ISSUE THREAD

**Issue by nsordk** [JimBobSquarePants/ImageProcessor#751]
Using DiskCache,
7 days in maxDays,
TrimCache set to true

When I replace an image on the server images cached with a query remains the old image, but image without query changes perfectly.

Image with query is:
/resources/product/UE4/9NU/UE49NU.jpg?width=1024&height=768&bgcolor=fff

- ImageProcessor version: 2.5.6.0
- ImageProcessor.Web version (if applicable): 4.8.7.0
- Environment (Operating system, version and so on): Windows Server
- .NET Framework version: 4.7.2

**Comment by JimBobSquarePants** [comment]
What is the response from the browser? Has the cache expired?

**Comment by nsordk** [comment]
From the image with query:
ETag: "acc22f47b530d51:0"
Expires: Wed, 10 Jul 2019 08:22:13 GMT
ImageProcessedBy: ImageProcessor/2.5.6.0 - ImageProcessor.Web/4.8.7.0
Last-Modified: Tue, 02 Jul 2019 09:06:14 GMT

Image without query:
ETag: "cd3e9066b530d51:0"
Last-Modified: Tue, 02 Jul 2019 09:06:14 GMT

**Comment by nsordk** [comment]
It seems that the original image doesn't go through imageprocessor, is this why the cache itsn't trimmed when replacing the image?

**Comment by JimBobSquarePants** [comment]
I think you're misunderstanding how caching, especially browser caching works.

ImageProcessor.Web will intercept image requests only with valid querystring commands.
After processing the intercepted request the image is cached twice - Once on the server and once in the browser. 

The setting you have set to 7 days `maxDays` controls the server cache. A setting `browserMaxDays` controls the browser cache. See the configuration example in the docs:

https://imageprocessor.org/imageprocessor-web/configuration/#cacheconfig

When an image is cached in the browser **it does not make subsequent requests to the server until the cache has expired**. In your case you can see that the browser cache will expire on the 10th July 2019 which is in the future.

Once the browser cache has expired, the browser will make a request to the server. If the source image has changed, then ImageProcessor.Web will detect that change and reprocess the source image overwriting the cached output. 

Trimming the cache only removes expired images.

So, if you want to see immediate changes then you should set the browser `browserMaxDays` to 0 or better still, control the generation of image urls  based on the last edit time of the  model containing your image by appending an additional  `rnd={YOUR_MODEL_LASTWRITETIME.Ticks}` parameter.  That will allow your browser to cache the images reducing server load and detect changes since the request url is now different.

Does that make sense?

**Comment by nsordk** [comment]
Hi James,

Thank you for taking the time to explain this to me.

My regrets about the old versions, I will try to do an update now.

**Comment by JimBobSquarePants** [comment]
No worries, and good luck. If you have further issues please let me know.

**Comment by DennisGlindhart** [comment]
@JimBobSquarePants @nsordk 

I've investigated this further as we have seen this issue come up on a regular basis where browserCache can't explain it alone and found the explanation.

cache.config Configuration:
```
<cache name="DiskCache" type="Chainbox.App.Webshop.Custom2DiskCache, Chainbox.App.Webshop" maxDays="3" memoryMaxMinutes="1" browserMaxDays="1">
   <settings>
     <setting key="VirtualCachePath" value="~/app_data/cache" />
   </settings>
</cache>

```
Steps to reproduce (Assuming this is done after 01.01.2019)
1. Put picture (/images/pic.jpg) on disk with system/filesystem ModifiedDate = 01.01.2019 12:00 on disk
2. Request image (/images/pic.jpg?width=123) in browser
3. Replace existing picture on disk with newer system/filesystem ModifiedDate i.e 01.01.2019 13:00 (Newer than original picture)
4. Request image (/images/pic.jpg?width=123) in browser (Caching disabled). Result: Old image still shown

I've put a debugger on it and found the following explanation:

https://github.com/JimBobSquarePants/ImageProcessor/blob/master/src/ImageProcessor.Web/Caching/DiskCache.cs#L149 seems to check if the image is newer than the current (old), but the dates that are actually compared are the modifiedDate of the new image (01.01.2019 13:00) against the time when the **cached** image has been generated - not the modifiedDate of the old image.

Thus for the cache to "trigger" (generate/show the new image) one must replace the existing image with an image with a modifedDate higher than the time when the cache is generated.
In theory for this to function 100% of the time you must make sure that the newly uploaded image gets it's modifiedDate set to NOW on the filesystem when the image is uploaded/put on the disk.

Don't know if this is expected behaviour or not - it wasn't clear to us that this was what was actually happening, but now we at least have a "workaround" with this knowledge.

Hope this can help others.

**Comment by JimBobSquarePants** [comment]
> the dates that are actually compared are the modifiedDate of the new image (01.01.2019 13:00) against the time when the cached image has been generated - not the modifiedDate of the old image.

This is expected. Since no metadata is stored along with the cached image the only thing we have to compare to is that image. An updated replacement for an image is commonly created after initial caching so this is the best approach in most situations.
