### ISSUE TITLE
Batch processing best practice

### ISSUE THREAD

**Issue by valse** [JimBobSquarePants/ImageProcessor#775]
Hi, I made a windows service to resize some images in batch; I tried the `ImageFactory` loading the image `source` path like this:

``` c#
using (var imageFactory = new ImageFactory(true))
{
	imageFactory
		.Load(source)
		.AutoRotate()
		.Resize(new ResizeLayer(
			new Size(width, height),
			ResizeMode.Crop
		));

	if (quality.HasValue)
	{
		imageFactory.Quality(quality.Value);
	}

	imageFactory.Save(source);
}
```
and then I tried to read all image's bytes first and then using a `MemoryStream`:
``` c#
var photoBytes = File.ReadAllBytes(source);

using (var inStream = new MemoryStream(photoBytes))
{
	using (var outStream = new FileStream(
		source,
		FileMode.OpenOrCreate))
	{
		using (var imageFactory = new ImageFactory(true))
		{
			imageFactory
				.Load(inStream)
				.AutoRotate() //takes care of ex-if
				.Resize(new ResizeLayer(
					new Size(width, height),
					ResizeMode.Crop
				));

			if (quality.HasValue)
			{
				imageFactory.Quality(quality.Value);
			}

			imageFactory.Save(outStream);
		}
	}
}
```
I saw that using the source path directly the service doesn't release the loaded memory, instead the `Stream` version use less memory... what is the difference and is it correct to read all bytes first?
Thanks

**Comment by JimBobSquarePants** [comment]
Hi @valse Sorry for the slow reply.

Using the source path directly mean that System.Drawing keeps a lock on the input file memory until the everything has been disposed. Reading all the bytes and creating a new memory stream means that memory can be released by the GC once the ImageFactory has copied the data into an internal stream.

I think the approach you are using loading up the bytes is the best approach. By passing the byte array directly the memorystream does not allocate extra data since it knows the length of the input byte array.
