### ISSUE TITLE
ImageProcessor images lose quality

### ISSUE THREAD

**Issue by mirko2609** [JimBobSquarePants/ImageProcessor#790]
Hi James, I've some problem about the quality.
The quality of the resized picture is not the best, I tryied before with an image jpeg 
http://mb-website.com/prova.html
and then with one .jpg took from my iphone X. 
http://mb-website.com/prova2.html

Could I add something to get a better result?
Thank you

ImageProcessor (2.8.0), ImageProcessor.Web (4.11.0), ImageProcessor.Web.Config (2.6.0), I dont use visual or whatever program, everything done by myself, the web.config is:

```
<?xml version="1.0" encoding="UTF-8"?>

<configuration>

  <configSections>
 <sectionGroup name="imageProcessor">
      <section name="security" requirePermission="false" type="ImageProcessor.Web.Configuration.ImageSecuritySection, ImageProcessor.Web" />
      <section name="processing" requirePermission="false" type="ImageProcessor.Web.Configuration.ImageProcessingSection, ImageProcessor.Web" />
      <section name="caching" requirePermission="false" type="ImageProcessor.Web.Configuration.ImageCacheSection, ImageProcessor.Web" />
    </sectionGroup>
  </configSections>
  
  <system.web>
    <httpModules>
      <add name="ImageProcessorModule" type="ImageProcessor.Web.HttpModules.ImageProcessingModule, ImageProcessor.Web"/>
    </httpModules>
  </system.web>
  
  <system.webServer>
  <validation validateIntegratedModeConfiguration="false" />
    <modules>
    <add name="ImageProcessorModule" type="ImageProcessor.Web.HttpModules.ImageProcessingModule, ImageProcessor.Web" />
    </modules>
  </system.webServer>
  
<imageProcessor>
    <security configSource="config\imageprocessor\security.config" />
    <caching configSource="config\imageprocessor\cache.config" />
    <processing configSource="config\imageprocessor\processing.config" />
  </imageProcessor>

</configuration>
```

The cache.config, and processing.config are not modified.

In the security.config I have added 
```
      <whitelist>
             <add url="http://images.pexels.com"/>
      </whitelist>
```
I put them in root/config/imageprocessor

**Comment by JimBobSquarePants** [comment]
@mirko2609 

A couple of points I must make before we engage in any future conversation.

1. Don't change issues on-the-fly. You opened an issue with one problem and have now changed it to another doing so is a waste of maintainer time.
2. **Don't ever email me to pester me to look at your issues**. You opened your first issue at 12:35am local time Sydney and emailed me only 2 hours later asking me to look at it. You can tell where in the world I live and the time zone I am subject to  because it is listed on the same page as my email address (I have since removed that email address). You have since sent me subsequent emails. **That is not acceptable behavior**.

Now, in answer to your issue. You've reduced the image dimensions by 33% so have removed a large portion of the pixel data. The System.Drawing resampling method does not work particularly well when resizing certain images but we are stuck with it so cannot change anything there. I would suggest enabling and using the `GaussianSharpen` web processor to sharpen up the images slightly after resizing.

**Comment by mirko2609** [comment]
Thank you for the answer and sorry for my behaviour, I dont use to stay on this forum so that s why I tryied to push up my question, I wasnt sure you still check this forum, sorry again.
I have tried with sharpen=10&sigma=1.5&threshold=10 or sharpen=100&sigma=1.5&threshold=10 but looks they are not better then before.
Yes, the picture with coronza it has be resized a lot but the other not, they dont have both professional quality

**Comment by JimBobSquarePants** [comment]
No worries.

I've opened a new issue #792 to cover this as the new rewrite produces better output. I'll investigate the cause of the difference using your images.
