### ISSUE TITLE
Request: Multi-page TIF Support

### ISSUE THREAD

**Issue by zkost** [JimBobSquarePants/ImageProcessor#798]
Does the ImageProcessor suport reading and writing multipage TIF files? If not, can this feature be added to the library? If present, I have not been successful in finding a reference to it in either issues or the documentation. Please advise!

Great Library!

Thank you
Ben

**Comment by ronaldbarendse** [comment]
ImageProcessor can only do what `System.Drawing` does, which does seem to support multi-page TIFFs. Selecting different pages can be done using [`image.SelectActiveFrame(FrameDimension.Page, pageIndex)`](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.image.selectactiveframe), but saving seems to require some more work: https://stackoverflow.com/questions/398388/convert-bitmaps-to-one-multipage-tiff-image-in-net-2-0.

As far as I know and can see from the source, ImageProcessor doesn't support this out of the box (using the fluent syntax). However, this library is in maintenance mode, so if it doesn't, it also won't get added as new feature. You can always access and manipulate the `System.Drawing.Image` or write your own processor or image format, so that still gives you some options.

**Comment by JimBobSquarePants** [comment]
The V2 architecture wouldn't support multipage Tiff but the V3 architecture could. 

V3 is being delivered slowly though as focus is very much elsewhere
