### ISSUE TITLE
Resize and rotation problem

### ISSUE THREAD

**Issue by animha** [JimBobSquarePants/ImageProcessor#803]
Hello, I'd like to report a strange issue that occurred to me. 
This is somehow linked to issue #538 

I'm doing some automatic thumbnail generation, and my thumbs were generated with some unwanted rotation in it. I tried various combinations: preserve EXIF, Autorotate (on both thumbnails and original image) with no success.

Then I noticed that in issue #538 you were loading image directly from filesystem. I was loading it from a System.Drawing.Image.

```
using (FileStream fs = new FileStream(img, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
using (Image image = Image.FromStream(fs))
using (ImageProcessor.ImageFactory imageFactory = new ImageFactory())
{
  imageFactory.Load(image);
...
```

In this way, I had no way to make it work properly. 

In this case, using an Image is actually useless, because I have a real file on filesystem; So I easily solved it by following your example and replace all with a simpler: imageFactory.Load(pathtoimage).
Often I only have a binary stream (if I store my images on db for example), and this could be an issue.

I attach the original file. 
Thanks,

![8053805452385](https://user-images.githubusercontent.com/5971094/80349698-e7355180-886f-11ea-98a0-22f10c0a0b4f.JPG)

**Comment by ronaldbarendse** [comment]
Like in the linked issue (#538), you need to remove the EXIF data if you're using `AutoRotate()`, otherwise the image data will be rotated, but because the EXIF is not updated/removed, it will be displayed in the 'wrong' orientation in most programs.

ImageProcessor supports loading from file paths, streams, byte arrays and `System.Drawing.Image`, so that should support storing your images in a database.

If you're still having issues, please post complete example code or better yet, create a unit test that fails and indicates the problem, so it can be fixed without breaking other tests.

**Comment by ronaldbarendse** [comment]
Just checked the original image and that contains `<tiff:Orientation>1</tiff:Orientation>`. The embedded image on this page displays the image rotated, but when you open the image in a new tab (or other program), it looks at the EXIF data and automatically rotates the image for you.

ImageProcessor can also automatically rotate the image for you, but you'd need to removed the EXIF data to make sure other programs don't rotate the already rotated image data...
