### ISSUE TITLE
Webp is not work with .netcore 2.2

### ISSUE THREAD

**Issue by mk148a** [JimBobSquarePants/ImageProcessor#806]
### Prerequisites

- [ + I have written a descriptive issue title
- [ +] I have verified that I am running the latest version of ImageProcessor
- [ +] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [+ ] I have searched [open](https://github.com/JimBobSquarePants/ImageProcessor/issues) and [closed](https://github.com/JimBobSquarePants/ImageProcessor/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Hi there, i try to convert my images to webp with your plugin.
 using (var webPImage = new ImageFactory(preserveExifData: false))
                                    {
                                        memoryStream.Position = 0;
                                        webPImage.Load(memoryStream)
                                            .Format(new WebPFormat())
                                            .Quality(90)
                                            .Save(Directory.GetCurrentDirectory() + path);
                                    }
with like that but i try to make process i got that error:
The type initializer for 'ImageProcessor.Plugins.WebP.Imaging.Formats.NativeMethods' threw an exception.

### System Configuration

- ImageProcessor version:latest
- ImageProcessor.Web version (if applicable)
- Other ImageProcessor packages and versions:latest
- Environment (Operating system, version and so on):windows server 2019
- .NET Framework version:2.2
- Additional information:

**Comment by JimBobSquarePants** [comment]
There’s no such thing as .NET Framework 2.2 it looks to me like you are attempting to run the library on .NET Core which is explicitly not supported.

**Comment by douglasg14b** [comment]
@JimBobSquarePants 

>it looks to me like you are attempting to run the library on .NET Core which is explicitly not supported.

Can you please document this, so it's **explicit**?

Ie.:
> *ImageProcessor does not support .Net Core*

**Comment by douglasg14b** [comment]
Does this also mean that the up and coming .Net 5 will not be supported as well? As it's a replacement of classic .Net with Core from my understanding.

**Comment by c9mbundy** [comment]
Is imagesharp.web intended to be an alternative option for migrating to .Net Core ?

**Comment by ronaldbarendse** [comment]
> Is ImageSharp.Web intended to be an alternative option for migrating to .NET Core?

One of the alternatives yes, although it's definitively not a drop-in replacement. ImageSharp is created by the maintainer of ImageProcessor, hence the reference in the readme.

**Comment by JimBobSquarePants** [comment]
> Is imagesharp.web intended to be an alternative option for migrating to .Net Core ?

@c9mbundy I'm assuming you mean as a replacement for ImageProcessor.Web ? (ImageProcessor and ImageProcessor.Web are separate libraries). So yes, but as @ronaldbarendse  says, it's not a drop-in replacement. It's middleware that accepts a (comparatively limited but extensible) series of URL commands to perform processes. It's a much smarter and faster implementation of the web component of this library.

>@JimBobSquarePants

>>it looks to me like you are attempting to run the library on .NET Core which is explicitly not supported.

>Can you please document this in the readme, so it's explicit?
>
>Ie.:
>
>>ImageProcessor does not support .Net Core

@douglasg14b This is an [**open source**](https://opensource.com/resources/what-open-source) library. There's nothing to stop you submitting a PR to do so. (Nuget is explicit about supported target frameworks btw)

.NET 5 is .NET Core plus the best of Mono and Xamarin. System.Drawing.Common is a leaky abstraction over individual graphics APIs on different platforms. Its feature set is not guaranteed across different platforms and neither is the ouput of operations. I wouldn't support it even someone paid me to do so and since on-one is.... Well. It ain't ever going to happen.
