### ISSUE TITLE
JPG image displaying as a black box in the media section

### ISSUE THREAD

**Issue by villian** [JimBobSquarePants/ImageProcessor#827]
### Prerequisites
![image](https://user-images.githubusercontent.com/6407659/104972262-e645e080-59f9-11eb-8d27-ee40542fa621.png)

We have quite a strange issue with Umbraco 7.15.4 and JPG files; they are showing as a black box in the back-office. We use Azure blob storage for images. PNG works fine. The problem only with JPG.

Upgraded Umbraco to 7.15.6
Upgraded ImageProcessor to 2.9.1
PostProcessor is not used

**Comment by JimBobSquarePants** [comment]
I would raise this issue in the Umbraco tracker. They are responsible for generating queries.

**Comment by villian** [comment]
when I test the media url in the browser it works

if I add ?width=100 it returns a black image 100px

**Comment by JimBobSquarePants** [comment]
Here's a running query from the test website in the dev branch. This reflects the build. As you can see it works.

https://github.com/JimBobSquarePants/ImageProcessor/tree/develop/tests/ImageProcessor.TestWebsite

![image](https://user-images.githubusercontent.com/385879/104977915-9a466c00-59f8-11eb-806f-e9b542470da0.png)

I notice you do not mention upgrading ImageProcessor.Web

Perhaps if you had used the template I provided (instead of rudely deleting it) you would have noticed that this a requirement.
