### ISSUE TITLE
Feature/Question/Idea: Disable disc cache based on query string parameter

### ISSUE THREAD

**Issue by enkelmedia** [JimBobSquarePants/ImageProcessor#831]
### Description
I'm working on a project where we need to display "previews" of the image end result, the editor can adjust settings to see who this looks after ImageProcessor have performed it's magic.

For this scenario we might see editors performing 5-10 image renderings (with different settings) that will never be used again, only the "end result" will be used on the front end.

I was thinking that maybe there could be a way to just have ImageProcessor perform the processing but not store the file on disk, after looking into the source I can see that there is the "ipignore=true"-concept and I'm looking for something like a "ipnocache=true" =D

Reading the source I can see that after the processing the request is redirected to the image that is the "result" of the processing so I guess that my wish here is quite far away since there need to be a file to redirect to?

Any way, I wanted to post this here to see if there might be something that I'm missing or if I can do something to archive what I'm looking for? 

Also to check if this is something that could/would be considered for a PR in the future?

**Comment by ronaldbarendse** [comment]
@enkelmedia You could try lowering the `MaxDays` setting to remove all cached images more aggressively, so these unused images won't be kept for the default 365 days (assuming you also have cache trimming enabled). This uses an absolute value based on the creation date, so even actively used images will be removed and will need to be regenerated quicker though, which is probably not what you want.

There's a similar issue when the original image file is removed: the cached images aren't removed automatically (which might be problematic if this image was removed because it contained personal or confidential information, etc.).

Having a way to remove all cached images based on the original file path (without query string parameters) would allow both issues to be fixed at the same time (although you would need to manually request the removal of the cached images or do the processing on a temporary file).

@JimBobSquarePants AFAIK the cached image paths are based on a hash of the full URL, so I guess the file names would require separate hashes of the file path and query string parameters to be able to do this, right?

**Comment by JimBobSquarePants** [comment]
My concern about adding a querystring value would be that you've now exposed a known attack vector for DDOS. 

Me... I'd tag `v=[value]` to the end of the request in your previews and forget about the fact the cached result is never reused.

**Comment by enkelmedia** [comment]
True story, that would be an attach vector...

Thanks for getting back, I was quite sure that this was a hard one to get right.

**Comment by enkelmedia** [comment]
@ronaldbarendse
