### ISSUE TITLE
Processing PNGs Can Dramatically Increase File Size

### ISSUE THREAD

**Issue by DanDiplo** [JimBobSquarePants/ImageProcessor#98]
I'm using ImageProcessor 4.0 within the context of a CMS (Umbraco) where I automatically put every editor-added image through IP (to ensure the image fits the placeholder dimensions and also to reduce the size, by setting a default quality, of all images). This works brilliantly for JPEGs, but for PNGs adding _any_ type of processing can dramatically increase the file size. As an example take these two PNG images:

http://h2energy.phusemarketing.co.uk/media/28354/tank-arrangements-1.png (original 558 x 435 **84.5KB**)

http://h2energy.phusemarketing.co.uk/media/28354/tank-arrangements-1.png?width=558&height=435&quality=75 (processed **141KB**)

You'll see the processed PNG is 65% _larger_ in file size. Changing the quality setting appears to have no effect.

Obviously in this case the "resized" image is being served at the same dimension as the original, so there is no actual gain, but because processing is applied globally across the site this can happen.

Is it just bet to leave PNGs alone if they don't require resizing?

**Comment by JimBobSquarePants** [comment]
I'm gonna close this as wontfix as writing a completely new png parser is out of scope for the project. We have the PostProcessor plugin for web environments also.

**Comment by nielslyngsoe** [comment]
Hi @JimBobSquarePants 

I´m having a related issue, in Umbraco Cloud, I´m sorry I dont know how to get the version number of ImageProcessor. But its running Umbraco 7.5.13.

I have successfully requested a PNG image with Quality=50 and it really shrinks the size, so thats great, from 430kb to 160kb.
But if I combine that with a resize it looks like the Quality doesn't have an effect. Cause turning quality on/off doesn't change the size (compressed and non-compressed output are both 160kb)

I´m thinking maybe the Quality is applied before resize and therefor lost in the resizing? or maybe it just doesn't work together with resize.

I hope you at one point will have time to look into this, it would be so great if we could do compressed PNGs on the fly.

Here is the two example links:
https://nolz-test.s1.umbraco.io/media/1002/frame0000.png?quality=50
https://nolz-test.s1.umbraco.io/media/1002/frame0000.png?quality=50&height=600

Thanks a lot, and just let me know if you have any questions.

**Comment by JimBobSquarePants** [comment]
Hi @nielslyngsoe 

The order of is imperative but that's not your issue here. Quality does not actually affect png files since they are not lossy like jpeg.

You first image is actually a well quantized, well dithered png file weighing in at only 93.2kb

https://nolz-test.s1.umbraco.io/media/1002/frame0000.png

Your first example request actually reencodes the image to 32bit rgba making the image larger at 161kb

https://nolz-test.s1.umbraco.io/media/1002/frame0000.png?quality=50

The resized image is weighs less than the first example only because it is smaller at 156kb

https://nolz-test.s1.umbraco.io/media/1002/frame0000.png?quality=50&height=600

The command you are actually looking for is [format](http://imageprocessor.org/imageprocessor-web/imageprocessingmodule/format/)

https://nolz-test.s1.umbraco.io/media/1002/frame0000.png?height=600&format=png8

This quantizes and reencodes the image as an indexed file much reducing the filesize to 26.5kb although, unfortunately, the output will not be as good as the original. This is due to the lack of dithering support in the quantizer used by the library. 

I've been doing a lot of work in that space though with my new imaging library ImageSharp and can using that produce [smaller images with equivalent quality](https://github.com/JimBobSquarePants/ImageSharp/pull/173#issuecomment-293817306) than the industry standard. I may, one day, be able to find the time to backport that functionality into ImageProcessor. 

I hope this all makes sense

Cheers

James

**Comment by nielslyngsoe** [comment]
Hi @JimBobSquarePants 

Very great feedback, thanks. And it defiantly makes sense, I see that PNG8 really hurts the quality in a way that is not good enough for the this specific purpose, but I might use it for something in the future. I would really love to be able to use a compression like "pngquant" or simelar in Umbraco, so defiantly let me know when it arrives.

The reason for me to ask is because I have been using this website: tinypng.com, which does simelar stuff, but it really compresses a PNG, down to around 20% of original size. But just not on the fly. For us it would be really great to be able to compress in that format on the fly. Maybe you can figure out what they are doing to make it so small but still keeping a acceptable quality.

Thanks

**Comment by JimBobSquarePants** [comment]
Oh you can use my post-processor for that! :smile:

Install the nuget package and any newly processed images will run through the various tool to reduce file size. Give it a pop and let me know how you get on.

Cheers!

P.s I know how they do it, it's just not fast enough that's all. 

http://imageprocessor.org/imageprocessor-web/plugins/postprocessor/
